### ISSUE TITLE
Worklog goes out of sync

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#1]
Worklog goes out of sync when it is updated or deleted directly in Jira Server

**Comment by shridhar-tl** [comment]
This functionality is implemented and is available from version 0.46 onward. In case if someone find any issue with this feature then please add a comment in this ticket along with the details of the issue you faced.

**Comment by shridhar-tl** [comment]
Closing this ticket as no issues were reported against this ticket.

**Comment by yaroslav-nuznenko-axon** [comment]
I had some logs and Logged out from Jira Assistant. Then Re-Login and all my logs were lost. How can I restore my logs? (or maybe import it from Jira)
