### ISSUE TITLE
Add "Only viewable by" option to worklog comments

### ISSUE THREAD

**Issue by ElPincheTopo** [shridhar-tl/jira-assistant#102]
When I add a comment or coment for a worklog in Jira There is an option under the comment to restrict who can view this based on user roles. It would be great if this was also implemented on the Jira Assistant.

It's annoying for people watching the ticket to get alerts about people logging time to the ticket, but if the comment was restricted to a group of people like devs, then the business people won't get the annoying alerts every time this happens.

**Comment by shridhar-tl** [comment]
Hi @ElPincheTopo - I know it is very late to respond and apologies for that. Last year I have added an option to disable sending notification to other users based on configuration from general settings page worklog tab. However I was not able to find "Only viewable by" option in Jira. Can you send a screenshot or some additional details about it?

Once I have it enabled in Jira and have a look at it, I would be able to figure out how to get it implemented in JA. However, if this is a feature from some of the addon's, then I would not be able to implement it as JA does not try to use / extend feature of addons.

I am closing this issue for now as I believe this is not a feature from Jira. Please feel free to reopen this ticket by adding more details, if you believe this is a feature within Jira.
