### ISSUE TITLE
Extensions does not work with activated MultiAccount Containers and Temporary Containers

### ISSUE THREAD

**Issue by afischer211** [shridhar-tl/jira-assistant#103]
I try to use this extension with my current Firefox 70.0.1 with installed and activated extensions "Firefox Multi-Account Containers" and "Temporary Containers".
So the Jira-pages are opened automatically in a specific firefox container and are also authenticated. But the jira-assistant can not detect the succesful authentication. I think, the extension runs in another container/context and can not use the successful authentication from the other container.

**Comment by shridhar-tl** [comment]
Hi @afischer211 - If I understand you correctly, containers are used for the exact purpose to block cross container cookie / other storage access. So you will have to be authenticated with Jira in the same container as that of where the extension is running. You cannot access the cross container authentication.

Hope I answer your question. If it is not relevant, I would request for more details.

**Comment by afischer211** [comment]
Hello, thanks for your answer. But how can I define the used container for this extension? I get (before the first view) the popup for finishing the integration (input the url) and can not set or modify the used container. So I must set the used container in extension settings (how?) or the integration settings (define jira-url and push button for integration) should integrated in a normal browser-tab instead of a popup.

**Comment by afischer211** [comment]
The same extension runs without problems on other chromium-based browsers (which does not have the multi-account containers). What can I do to run the extension in the same container like my normal jira page?

**Comment by shridhar-tl** [comment]
Unfortunately as Multi Container doesn't support setting default container for Extensions, their is no straight forward way. But you can do a bit workaround to use it which is as follows.

First you should open Jira and authenticate with it in a container. Then open a new tab in same container and open Integrate page of Jira Assistant in that tab directly using the following url: moz-extension://6954ddfc-8465-4bc8-82c0-a6ecf20cc77a/index.html#/integrate

Now you can provide the url of Jira in the field and click Integrate button and it should get integrated.

But this is not all what you will have to do. After integrating with Jira also, every time you open Jira Assistant, first open the empty tab using the same container first and then click on the menu under JA icon. If you did not open a empty tab, then clicking on the menu will open a separate tab which will not use the same container and Jira Assistant will not work.

Until Multi Container support setting default container for extensions, at this point, I couldn't think of any way around this as this is not the limitation with Jira Assistant, but with Multi Container itself.

**Comment by shridhar-tl** [comment]
Hi @afischer211,  As I did not hear from you, I hope you are good with my reply and hence closing this issue. In case of any thing else, please feel free to reopen it or raise a new issue.

**Comment by ZeeD** [comment]
Hi @shridhar-tl 
I tried following your advice to "manually" set the `moz-extension://` url in a container tab.
Unfortunately it seems it doesn't work: on ff 92.0.1 I cannot set the url. The tab simply refuses to load the url

**Comment by mhogerheijde** [comment]
@ZeeD  I've got the same issue. It seems the ID of the extension has changed maybe? For me it is:

`moz-extension://82db3c8e-18e2-4832-86b8-ee6ea1770926/index.html`

Hoewever, @shridhar-tl, it seems that the proposed solution does not work for me.I have both 
`moz-extension://82db3c8e-18e2-4832-86b8-ee6ea1770926/index.html` and my companies jira open in the same container, but pressing the button opens the extension in a separate container again.

It is probably made worse by me using the setting to always open jira in my _work_ container. So I'll try to un-set that so it will allow it to open containerless too. Let's see if it at least prompts me to log in.
