### ISSUE TITLE
Worklog fails for users with apostrophe in email/Jira username

### ISSUE THREAD

**Issue by bilbo13** [shridhar-tl/jira-assistant#107]
![JiraAssistant_ErrorWithApostrophe](https://user-images.githubusercontent.com/58404460/69921801-bc72d880-144a-11ea-99c3-e441b916a2a6.jpg)

We have a user with an apostrophe in his username/email:  jo'connor / jo'connor@sieinc.com.

I have added this user to a Group, and the Worklog report throws the error in the attachment:

Error fetching ticket details
Error in the JQL Query:  Expecting ',' or ')' but got 'connor'. (line 1, character 92)

Thank you!!

**Comment by shridhar-tl** [comment]
Hi @bilbo13 - Can I know what is the version you are using? This issue has been resolved in version v0.88 and published yesterday. Please check if you have the latest version and retry once again and let me know if you still face this issue.

**Comment by bilbo13** [comment]
Hi @shridhar-tl - I updated to the latest version.  This is resolved!
Thank you!!
