### ISSUE TITLE
Update layout of Worklog entry and tab order

### ISSUE THREAD

**Issue by EH-DUMAC** [shridhar-tl/jira-assistant#108]
I rarely need to modify the Log time and time spent when creating a worklog, so was wondering if they could be grouped together, and moved to the end of the tab order?

If the Tab Order can be set however you need it, regardless of where the fields are, then I could see these two fields at the top, but the Ticket no field is the first in tab order, so you could shift+tab to get back to these fields, if needed.

Additionally, it would be nice if the Ticket no field could be the default field with focus when Worklog form is displayed so you can immediately start typing, then tab once to get to and enter comments, and then tab once again to get to save button.

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC - I had implemented auto focus for ticket number field. I would publish the changes based on other enhancements / fixes available (max by end of this week). Once your version of Jira Assistant gets updated to v.0.91, you will see this change. I am not clear if you requested anything else additionally.

**Comment by EH-DUMAC** [comment]
Great on the auto focus issue.

The other part of my request was to move the "Time spent" field up above the ticket number field to the right of the "Log time", since I believe those to be rarely changed, thereby reducing the number of times Tab key is needed to edit and save a new worklog entry.

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC - Their are other places in the application from where worklog can be added and their users will have to enter timespent by them self and ticket number will get auto populated. So moving the fields are not the right solution. If you want the key press to be reduced, then I can provide an alternate solution. I would allow saving worklog by pressing enter key at any point. Hope that would solve your purpose.

Let me know your thoughts about it.

**Comment by EH-DUMAC** [comment]
My main issue is having to press Tab 3 times to go from the ticket no to comment field, since I rarely override the time spent.  Can the placement of the time spent field be dynamic depending on where the worklog is opened, or possibly configurable via the calendar configurations screen?

I am not opposed to also having enter key save the ticket, but if you do that, I would suggest something like Ctrl+Enter, so just pressing Enter in comment field does not save it prematurely if user wanted a line break in comment field.

**Comment by shridhar-tl** [comment]
Ctrl + Enter has been implemented for save. Will be available from v0.91 of Jira Assistant.

**Comment by EH-DUMAC** [comment]
Pressing Ctrl + Enter on the Override check box toggles the check box, it does not save the ticket.  Can this be changed?

Also, here is an image of a suggested screen change, although as you said, not sure if this would work for everyone or not:

![image](https://user-images.githubusercontent.com/56832118/73498728-b08c8f80-4383-11ea-85b2-df7540d69a67.png)

Ticket No is first, since everyone needs to enter that.
Comment next, which can be optional.
Override Time is next, if needed.
Then logtime, if that needs to be set, such as from Month view.

**Comment by shridhar-tl** [comment]
There are technical limitations on the calendar control which is used. If it is shown at the bottom of the screen like in suggested mockup, when it is used with smaller screens, the popover is hidden at the bottom of the screen. So even after 3 years and updating to latest version of calendar, I was not able to implement it and hence closing this ticket. I will rethink about it at later point when feasible. Thank you for your suggestion.
