### ISSUE TITLE
Ability to set default value for 'Override Time Spent' field when adding Worklog

### ISSUE THREAD

**Issue by cliaz** [shridhar-tl/jira-assistant#109]
We use both the Calendar and the Daywise Worklog views to add worklogs, and then use the 'Override time spent' field to set the time spent.

In Calendar, the default value is 00:00
In Daywise Worklog, the default value is 01:00

We are logging work simply in 1d blocks (8 hours), and a customisable default value for those screens would save a lot of time.

**Comment by shridhar-tl** [comment]
Hi @cliaz - I know its too long but this implementation is done and would be available for extensions in next publish which would happen in another couple of days.

Special thanks to @orgads for his contribution in implementing this.
