### ISSUE TITLE
Issue key text shown twice when searching for issue while adding worklog

### ISSUE THREAD

**Issue by cliaz** [shridhar-tl/jira-assistant#110]
When searching for a issue while adding worklog, the issue key is displayed twice. For example, with issue key _RTO-157_, title _General Admin_, when searching for key '157' the following text is displayed:
_RTO-157 - RTO-157 - General Admin_

![image](https://user-images.githubusercontent.com/3636531/72494689-c759bf00-3878-11ea-8a6a-fe26805f9bd8.png)

**Comment by shridhar-tl** [comment]
I am still facing issue publishing to Chrome web store. But latest updates (i.e. v1.3) are published to Firefox, Edge and Opera already. Hope all the issues with Firefox should have already got resolved by now.

Chrome users please be patient or use Firefox version temporarily to help with your activities. Apologies for all the inconvenience caused.

**Comment by shridhar-tl** [comment]
This fix is published now in chrome extension as well. So you should see it working going forward. Thank you all for your patience. But for getting the fix published to chrome, some permissions given to chrome extensions were removed to get the approval in review process. As a result some of the minor features were removed as well. More in particular, Report Builder feature, excel export feature, first time integration, etc., may face some issues / change in the way of implementation.

To know exactly what is impacted, see version history in the extension.

**Comment by shridhar-tl** [comment]
Closing this ticket assuming this issues has been resolved now. If any of you still face any issue please feel free to raise a new ticket
