### ISSUE TITLE
(Add Worklog screen) Show issue key title after having searched for & selected it

### ISSUE THREAD

**Issue by cliaz** [shridhar-tl/jira-assistant#111]
When searching for a key while adding a worklog, the title is displayed:
![image](https://user-images.githubusercontent.com/3636531/72494869-51a22300-3879-11ea-8eb4-3a0bb1733102.png)

However once that key has been the selected, the title is not displayed:
![image](https://user-images.githubusercontent.com/3636531/72494975-a6de3480-3879-11ea-86f5-acff3091db1f.png)

**Comment by shridhar-tl** [comment]
Unfortunately implementation of this suggestion will need considerable effort and outcome value is small. Hence will be implemented only if popularity is more.

Anyone interested in this suggestion please +1 this issue. Also anyone interested is welcome to raise a PR with this change.

**Comment by shridhar-tl** [comment]
Hi @cliaz, this implementation is done in JA v2.44 and once your extension gets updated to latest version, you will start seeing the changes. Hence closing this ticket considering it is done.
