### ISSUE TITLE
AM and PM is not considering

### ISSUE THREAD

**Issue by ashokram** [shridhar-tl/jira-assistant#112]
Hi, it is not considering AM and PM, in the JIRA, I had given time as 03:30 PM of yesterday, but it is considering 03:30 AM of current day. Can you please check it.

**Comment by shridhar-tl** [comment]
Hi @ashokram, This is most probably due to the time zone difference between your system time and Jira Server. Just go to your Jira Profile and change your time zone to match your local timezone and it should be fixed.

**Comment by ashokram** [comment]
Thank you @shridhar-tl, after changing the timezone in JIRA, it worked fine.
