### ISSUE TITLE
Unable to get id of Parent issue of a Subtask. Selecting option "Parent" is not supported.

### ISSUE THREAD

**Issue by ankush2704** [shridhar-tl/jira-assistant#114]
Steps:
1. Create a custom report
2. Create a new Query
3 Add Parent in Display column

Note: Parent link is also not working. My objective is to get Parent ID of all my subtaskes so that I can group my sub-tasks. Please let me know how I can do it?

**Comment by ankush2704** [comment]
![image](https://user-images.githubusercontent.com/19248898/73137523-1674d080-407f-11ea-8fe8-bbfa7cb635d5.png)

**Comment by ankush2704** [comment]
@shridhar-tl please help, I am stuck due to this. I want to build a report where I can get ID and summary of parent task of all sub-tasks.

**Comment by shridhar-tl** [comment]
Merging this issue with #157. Based on new enhancement, this issue would get resolved.
