### ISSUE TITLE
Today the extension is not opening.

### ISSUE THREAD

**Issue by ccassio1977** [shridhar-tl/jira-assistant#115]
Just a blank page.
![2020-02-10_12h52_53](https://user-images.githubusercontent.com/58560551/74152224-bd23aa00-4c05-11ea-93a3-092942a9756c.png)

**Comment by sibirsky** [comment]
Same.

**Comment by kozinc** [comment]
[momjbjbjpbcbnepbgkkiaofkgimihbii-1581405778698.log](https://github.com/shridhar-tl/jira-assistant/files/4184466/momjbjbjpbcbnepbgkkiaofkgimihbii-1581405778698.log)
These are the errors shown:
TypeError: Cannot read property 'toLowerCase' of undefined
Global handler:- ErrorEvent
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by ArtemNorenko1982** [comment]
Same error since today morning
![Screenshot_3](https://user-images.githubusercontent.com/36227434/74234369-55d52b00-4cd5-11ea-8581-ca84daf4db08.jpg)

**Comment by tom-teamcoda** [comment]
It's because the worklog response remove name from Creator:

export interface Author {
  self: string;
  **name: string**;
  key: string;
  accountId: string;
  emailAddress?: string;
  avatarUrls: { [key: string]: string };
  displayName: string;
  active: boolean;
  timeZone: string;
}

**Comment by StephanMeijer** [comment]
Can we fix this asap? Can I help with anything?

**Comment by shridhar-tl** [comment]
Hello all, apologies for the inconvenience caused. I am not yet sure how this property could get removed from existing version of API. I would analyse and fix it ASAP. I am not sure if I would be able to spare time on weekdays. I would work on it this weekend and publish the change.

If any of you find more details please keep adding it so that it would help me make the changes quickly.

**Comment by RuslanLoboda** [comment]
@shridhar-tl I know that JIRA has removed user.name and getting data about user possible only by ID. That explanation i've got from friend that have app based on work with JIRA API. Hope, this information will help you to make fix.

**Comment by RuslanLoboda** [comment]
@shridhar-tl I know that JIRA has removed user.name and getting data about user possible only by ID. That explaination i've got from friend that have app based on work with JIRA API

**Comment by Tanatcu** [comment]
@shridhar-tl could you provide a little tutorial about building dev version of extension? Maybe somebody can solve the trouble locally and want to build dev version as temporal solution until you publish the fix?
Your extension as useful as you can't imagine :)
I'm really don't logging time to tickets cz waiting for your fix or tutorial for making temporal local version second day in sequence.

**Comment by ITGuyOhio** [comment]
Same here
![image](https://user-images.githubusercontent.com/60976097/74347954-e7997280-4d7f-11ea-8ff2-da5df7bd568c.png)

**Comment by tom-teamcoda** [comment]
The info https://confluence.atlassian.com/cloud/blog/2018/06/say-goodbye-to-usernames-in-atlassian-cloud

**Comment by tom-teamcoda** [comment]
Replace username with email address or userId will sort out

**Comment by ITGuyOhio** [comment]
Thank you for your response.
I already log into Jira with my company email address and Jira requires an
email to login, I cannot input a username. Where are you suggesting I
change the username/email?
Please advise
Matt Kinne

**Comment by vinaychavadi** [comment]
We are also awaiting the issue to be resolved at the earliest.

**Comment by shridhar-tl** [comment]
Unfortunately I was still able to see the user name in Atlassian cloud as well as in server instance as well with latest updates. So not able to reproduce it anywhere as of now. But already started to work on changes and hope to have it resolved ASAP. Will try to publish the changes by tomorrow EOD and will be available for users soon after web store review. Will keep you posted on the changes.

@Tanatcu - Steps for manual build is already available in github. You can refer to it. Url as follows:

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/CONTRIBUTE.md#guidelines-to-start-with-development

**Comment by shridhar-tl** [comment]
I had published the package (v0.94) in store and is currently in review. The time taken for review process is slower since couple of months and so I am not sure when it would be available. But I believe it should be available within next 4 days max.

It is available for multiple browsers and so temporarily you can use other browsers version if it is published. Below document contains the url for other browsers store listing.

https://github.com/shridhar-tl/jira-assistant#jira-assistant

**Comment by vinaychavadi** [comment]
@shridhar-tl  New version available on Chrome, but still getting the same error while try to access Jira Cloud. Are we missing something? Can you please look into it.

**Comment by shridhar-tl** [comment]
@vinaychavadi - Updates available in #119
