### ISSUE TITLE
Outlook calendar integration with tool for meetings

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#12]
Will be implemented based on popularity. If anyone feel this would be helpful then +1 this ticket.

**Comment by shridhar-tl** [comment]
This feature should be available for chrome user in one more week approximately.

**Comment by shridhar-tl** [comment]
This implementation has been done and is available since Jira Assistant v0.77 for Chrome.

Notes: This implementation is not fully done yet and it is still in BETA. Their are some known issues and flaws in this implementation.

Known Issues:
1) After integrated with outlook only for an hour the calendar details are pulled. After an hour the access token gets expired and unable to get a new token. Still trying to fix this issue.
2) Currently outlook events are displayed in the calendar and can be used to create automatic worklog entry. But still, meeting details are not displayed in the calendar when clicked on the outlook event. This functionality is yet to be implemented.

**Comment by alexanderpils** [comment]
Hey, I checked the Beta Version and besides the known issues it is already pretty need. I would have two suggestions as further enhancement. 

- That the description of the meeting is prefilled as the comment in the add worklog section

- If in the description of the meeting is a link to a Jira Issue, it will use this address as default in the add worklog section for the ticket number

Thank you already very much for this amazing tool. It makes the process of time booking really easy. The outlook integration would be the next step

**Comment by tomako** [comment]
Hey @shridhar-tl , this integration works very well in Chrome (thanks) but getting error in Firefox while authenticating "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application".

**Comment by guilhem88** [comment]
Hello @shridhar-tl, any updates on the known issues? This plugin works great but the token expiration issue makes it difficult to use...

**Comment by adelinardelean** [comment]
Hello, I got a question regarding Outlook calendar integration: when I try to set it up, I get the following message.

**Need admin approval**	
_Jira Assistant needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it._

 What access is required? I want to contact my organization admin  to request it.

**Comment by shridhar-tl** [comment]
Hello All, I know it had taken such a long time due to technical limitations we had and lack of options. But I am happy to let you all know that, outlook integration issue has been resolved. It would be available for you to use immediately in Web version of Jira Assistant if you are using JA Extension v2.38. In extension it would be available in v2.41 which may take couple of more weeks before I publish.

To know more about Web version, visit https://www.jiraassistant.com. To start using web version, visit https://app.jiraassistant.com.

**Comment by shridhar-tl** [comment]
Hi @adelinardelean - Its too late to respond. But may be my response helps others. This error message is shown if OAuth access to calendar is blocked by your organization. Unless apps are allowed to authenticate using OAuth, you won't be able to access it.

It's up to your companies security policy on whether they would allow this functionality or not and I won't be able to do anything about it.
