### ISSUE TITLE
When integrate Jira server with JIRA ASSISTANT it says one or more of the actions failed

### ISSUE THREAD

**Issue by Che994** [shridhar-tl/jira-assistant#123]
![jira](https://user-images.githubusercontent.com/42790577/74704929-1c05a680-5238-11ea-9b00-7696d16c6d95.png)

Yesterday morning it works fine and evening it was loaded so I have remove the extension and again install, after that this error message displays when I try to integrate

**Comment by Pankaj-111** [comment]
I am also facing the same problem

**Comment by sibtain5** [comment]
i am also facing the same problem .please tell me what to do

**Comment by andorini** [comment]
Update 0.94 same issue on Chrome!

**Comment by tinemlakar** [comment]
Chorme and Firefox. Reinstalled. Same issue.

**Comment by shridhar-tl** [comment]
Duplicate of #119 . Refer to the #119  for updates.

**Comment by Che994** [comment]
@shridhar-tl  any fix on this issue?
