### ISSUE TITLE
Worklog Report Hours showing incorrectly after latest update

### ISSUE THREAD

**Issue by npundra** [shridhar-tl/jira-assistant#125]
Worklog reports hours are showing incorrectly after latest update.

**Comment by piranha79** [comment]
npundra: latest update of the jira assistant or latest update of chrome?

**Comment by npundra** [comment]
Latest update of jira assistant that I tried in Firefox.

**Comment by npundra** [comment]
I tried in chrome and same issue. Worklog hours are showing incorrectly.

**Comment by npundra** [comment]
I tried v 0.96 in firefox and this seems to work as expected. Thank you very much.
