### ISSUE TITLE
no data showing (2)

### ISSUE THREAD

**Issue by devgurl00** [shridhar-tl/jira-assistant#136]
using latest version of Chrome and v.97 of JA. when i log in, i get a "you are not connected to the server error". that's one thing. then, when i pull a worklog report, i get data in the first tab, but not the second or third. this is a new thing that started maybe last week? can you help? i've got to have this information

**Comment by shridhar-tl** [comment]
@devgurl00 - Thank you for reporting this issue. This issue would be resolved in v0.98 of Jira Assistant which would be available within next week. If you face any of this issue after your version gets updated to v0.98, please send the details available in your browser console which would help me to debug the issue.

**Comment by shridhar-tl** [comment]
This issue has been resolved long back, but I am facing some issues in publishing and not able to get any support from web store team due to the current lock down situation as mentioned in other tickets. Hence their would be some more delays till the situation comes under control.

**Comment by shridhar-tl** [comment]
This fix is published now in chrome extension as well. So you should see it working going forward. Thank you all for your patience. But for getting the fix published to chrome, some permissions given to chrome extensions were removed to get the approval in review process. As a result some of the minor features were removed as well. More in particular, Report Builder feature, excel export feature, first time integration, etc., may face some issues / change in the way of implementation.

To know exactly what is impacted, see version history in the extension.

**Comment by shridhar-tl** [comment]
Closing this ticket assuming these issues are resolved now. If any of you still face any issue please feel free to raise a new ticket
