### ISSUE TITLE
Change columns in "my open tickets"

### ISSUE THREAD

**Issue by urscon** [shridhar-tl/jira-assistant#138]
Hi,
on the "My Open Tickets" Dashboard I dont see an option to set differen columns..
I'd love to see my fixVersion and DueDate.. 

The default is not so useful in my opinion. How can this be changed?

Default: 
Ticket No | Type | Summary | Reporter | Priority | Status | Resolution | Created | Updated

**Comment by shridhar-tl** [comment]
@urscon - It is not possible to change the columns in my open tickets, but is it possible using report builder. Please refer the following document. I am closing this issue for now, if you have any more questions you can post it.

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/SHARED_REPORTS.md
