### ISSUE TITLE
Firefox Add On is not available

### ISSUE THREAD

**Issue by viniciussilva-cit** [shridhar-tl/jira-assistant#139]
The URL for Firefox addon is no longer valid (not found):
https://addons.mozilla.org/en-US/firefox/addon/jira-assistant/

**Comment by michalfi** [comment]
Additionally, the addon can no longer be installed from here (https://github.com/shridhar-tl/jira-assistant/raw/master/release/firefox/JiraAssist_Latest.xpi) - Firefox will refuse the installation saying the addon is not verified

**Comment by kgorol** [comment]
2 weeks later no response, anything will be done about it?

**Comment by shridhar-tl** [comment]
@kgorol - I had already republished a new version for Firefox and Firefox team has rejected it. The reason behind it is their are lots of changes in review process and they do not accept some of the permissions I had used. So basically I am working on removing those permissions and as a result of that some of the feature may get removed. I am trying to find an alternate to continue to have the feature. I would be providing updates in couple of days about it.

For now, if you are very much wanting for it in Firefox, then you can use the alternate link available temporarily for Firefox which would continue to work and would continue to receive updates. 

@michalfi - I hope the issue you reported about unverified installation should have got resolved now. Please check and let me know if you face any other issues.

**Comment by kgorol** [comment]
@shridhar-tl thanks for the info! I hope you can solve issues somehow.

**Comment by michalfi** [comment]
@shridhar-tl Yes, the issue with unverified installation is resolved now, thank you.

Can we perhaps somehow help in your struggles with the Firefox team? e.g. flood them with some emails emphasizing how useful the extension is and how much we miss it :)

**Comment by shridhar-tl** [comment]
Thank you @michalfi. They wouldn't consider such mails. And by the way chrome also started to have similar but other restrictions. Their also they have rejected recent update to fix other minor issues. Already tried to publish 2 versions to both the stores and both were rejected. So Working on modifying the approach / removing some minor features.

**Comment by shridhar-tl** [comment]
Once again new version was published for Firefox. If review was successful then it may appear in Webstore. Hoping for the best.

**Comment by shridhar-tl** [comment]
Now once again Jira Assist is available in Firefox add-on store. But as a limitation, in this version, Advanced report builder won't work due to permission issues and I am in discussion with support team if they can allow me for this permission. I am not sure at this point if they would allow it. So, far now Except Advanced Report and some functionality in excel export will not work and all other functionalities will continue to work as expected.

Hope this solves the issue and hence closing this ticket. In case of any other issues, you can raise a new ticket.
