### ISSUE TITLE
Worklog not showing the efforts for the user after re-installing the JA 0.97

### ISSUE THREAD

**Issue by hclsathishkumark** [shridhar-tl/jira-assistant#141]
Worklog not showing the efforts for the user after re-installing the JA 0.97:
1. While clicking work log it is throwing error as :
Unable to connect to the server. Please check your network connectivity.- Network error
2. Ignoring the error, provided the date range, the effort is coming empty for the user.
3. Able to see the effort in the sprint report for the user.

Using the Chrome version 80.0.3987.132 (Official Build) (32-bit)

**Comment by shridhar-tl** [comment]
@hclsathishkumark - Please check your network tab while generating the report and see what is the response. Also please check the console and see if their are any error. Please provide the details and I will see what I could do. This is happening after the chrome update and so far I was unable to reproduce it my end and I get few reports about this issue. If someone who was able to reproduce it could give me some clue about the issue it would help me to resolve it.

**Comment by shridhar-tl** [comment]
This issue is related to #140 and #136

**Comment by hclsathishkumark** [comment]
I tried checking today, it is working now. No clue it's strange. Thanks for responding quickly Shridhar.
