### ISSUE TITLE
Add Work Log comment as a "Comment" not as "Work Log"

### ISSUE THREAD

**Issue by urscon** [shridhar-tl/jira-assistant#142]
Hi,
this is a little confusing. 
When people in my team use the function "Log work" and put a comment, this is not actually a comment, rather its put under "Work log" (see attached screenshot).
So the comment section is empty but the worklog is full of entries and normally we only look at the comments (especially in the board view where only limited information of a task is available during standups, so only comments are seen no work logs at all).
Is there a way to add the comments additionally in the "comments" section?

Thanks in advance!

![image](https://user-images.githubusercontent.com/61714112/76829981-a5eb6400-6824-11ea-9b5c-2b1056d98564.png)

**Comment by shridhar-tl** [comment]
@urscon - At this point their are no options in this extension to add comments. May be I would think about it and implement at later point. But for now, their are lots of issues to be addressed immediately and I am over occupied to think about any new features. I am closing this issue for now and will reopen it when I was able to.

To anyone looking at this issue - I am looking for support in handling bugs and feature requests. Anyone interested can raise a PR referring to the document.
