### ISSUE TITLE
Allow the Worklog report (and user group) to add inactive users

### ISSUE THREAD

**Issue by albertinsyd** [shridhar-tl/jira-assistant#143]
Firstly, thanks for an amazing tool in Jira Assistant.

I am using the Worklog Report to look at team work logged on a project typically by Month.  Occasionally users leave a project mid-month and are de-activated in Jira (but the user still exists).

I am unable to add these users to a worklog report, which means I can't see what they've done.

Would it be possible to modify the filter on add a user to a user group to remove the active/enabled user filter?  Respect that I wouldn't/shouldn't be able to modify worklog entries for these users, but it sure would be nice to report on them, as the work was done and logged.  Without this, it impacts my ability to do the reporting I need (clearly Jira can't do it either).  I'm relegated to going ticket by ticket and manually looking at the work log.

Thank you in advance!!

**Comment by albertinsyd** [comment]
P.S.  After doing some experimenting, I've realized that I can add a inactive user if I hit enter key.  From a UX perspective, usually the user would pop up before selecting/hitting enter.  But if I ignore the fact that nothing pops up and hit enter anyway, it seems to allow me to add the user.  This may be a documentation / training / user error.

**Comment by shridhar-tl** [comment]
I will look into this issue and resolve it if possible. Untill then hope the workaround you mentioned should help.

**Comment by shridhar-tl** [comment]
Closing this issue as latest ticket opened for same purpose and is on hold. More details available on #288.
