### ISSUE TITLE
Daywise worklog - sum total hours

### ISSUE THREAD

**Issue by namerci** [shridhar-tl/jira-assistant#145]
It would be really nice to have to sum all total hours in Daywise worklog (or any other kind of report). We can export report to Excel and sum it manually, so it's not urgent issue, but it will be really helpful to have it here.

The reason to have it in existing Daywise worklog is the date range. We will change one date range and it will update report and total hours.

**Comment by shridhar-tl** [comment]
Already worklog report have summed up total for hours logged, user wise, daywise, project wise, etc.. I am not sure where else you are expecting this feature. Can you please attach a screenshot for better understanding?

**Comment by namerci** [comment]
@shridhar-tl thanks for quick response! Hmm, maybe I'm doing something wrong, but I used Daywise worklog:

![image](https://user-images.githubusercontent.com/1153631/78030037-ca395b80-7361-11ea-8d03-92d41d285d51.png)

**Comment by shridhar-tl** [comment]
@namerci - This gadget is just to quick view for worklog. If you want a report kind of a view, then you should use Worklog report where you would be able to view report for multiple users along with multiple customization settings and summed up total.

**Comment by shridhar-tl** [comment]
I haven't heard from you since some time. I hope you are good with my reply and hence closing this ticket. In case of any other issue please feel free to reopen this or open a new ticket appropriately.
