### ISSUE TITLE
Report Builder functionality

### ISSUE THREAD

**Issue by ps2goat** [shridhar-tl/jira-assistant#147]
I'm trying to create a report that is basically the same as the worklog report, but with a few tweaks. I'm trying to parameterize dates, for example, and am not seeing exactly how to put that into my query. I did find the regex and found that I need to use `@Parameters.ParamName$` for Jira Assistant to find and replace them, but I get an error when trying to save the query.

```
Error fetching ticket details
Date value 'undefined' for field 'worklogDate' is invalid. Valid formats include: 'YYYY/MM/DD', 'YYYY-MM-DD', or a period format e.g. '-5d', '4w 2d'.
```

It looks like it's trying to run the query for the dataset immediately and fails. How can I get the query to not run until I View the report and provide parameters?

I'm on v0.97 for Chrome.

**Comment by shridhar-tl** [comment]
@ps2goat - It will run the query immediately to check if query is valid and to pull the data for preparing the dataset. Hence you can use the following pattern to execute the query.

@Parameters.ParamName.value|someDefaultValue$

Add a pipe symbol and add your default value after that which will be considered at design time. I kept this as an intern solution while thinking about an appropriate way to get this value from user. Also note that I had used "ParamName.value" before the "|" symbol. This ".value" may sometimes change based on then type of parameter. Hope this helps. Please let me know if you face any other issues.

Apologies for not having a documentation to explain these things. As it is still not fully functional, nothing is finalised yet and hence no documentation exists. Also availability of time is a bigger concern.

While keeping the Report Builder aside, can I know what is the additional functionality you are planning to build? If it is something useful for other's then I may try to accommodate it with Worklog report which would save lots of time for you as well.

**Comment by ps2goat** [comment]
Thanks, that default value did the trick for saving the query. I didn't test any further.

My report would use the data from "Flat" tab of the worklog report. (I had to make a usergroup to get this to show up, if others want to follow along.) The worklog report shows hours grouped per individual, my report would instead:

- Group issues and how much time has been worked against them.
- Times would be formatted like in JIRA, with weeks, days, hours, and minutes, using the configured values for work week and work day.

Most of the columns I need are in that "Flat" tab, so being able to choose which of those are displayed would be good, too. 
- Worklog comments would merge together in a single, bulleted list

**Comment by shridhar-tl** [comment]
Report builder module is incomplete due to the browser restrictions on using custom expressions. Hence at this point it is has lots of limitations and not feasible to provide much support on that. Hence closing this ticket as this being asked long back.
