### ISSUE TITLE
Access to browser history

### ISSUE THREAD

**Issue by vksiva** [shridhar-tl/jira-assistant#149]
For few of the tasks, Jira Assistant asks for permission to access browser history. Why is the access required?

Using chrome v80.0
Jira Assistant v0.97

**Comment by shridhar-tl** [comment]
Hi @vksiva - Jira Assist access the Jira Api with the url you provided and with the authentication you already have in your browser. This authentication is saved in your browser history. When we request permission for a url, by default browser provides access to history as well.  But Jira Assistant doesn't access any of your history information. It just tries to access the Api with browsers authentication which internally is happening through history. Hope it makes seance.

Please feel free to get back to me in case of any other doubts.

**Comment by shridhar-tl** [comment]
Hi @vksiva - Since I did not hear back from you, I hope you are satisfied with the reply and hence closing this issue. In case of any other queries feel free to reopen the issue or raise a new issue.
