### ISSUE TITLE
New report: Status wise time spent on individual issues

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#150]
A new report need to be create which would pull issues based on JQL and display tabular report in following format

Issue key, summary, [some more fields as necessary], Time spent in ToDo, Time spent in In Progress, [Timespent in other status as well similarly], Total time to close the story

Similarly a graph will be shown the summary of how much time was spent in each story in collection of all the tickets.

Anyone interested in this requirement please provide additional details / your requirements.

**Comment by shridhar-tl** [comment]
This report is implemented as a Gadget. So you can add it to Dashboard and view it. Graph is not added in initial MVP. If anyone is interested, then please leave a comment for graph related requirement. Also anyone interested can add additional requirements.

**Comment by palanid** [comment]
Shridhar, while using the Timespent on status gadget. After JQL input. Getting a error which says "One or more action failed".

Unable to load the timewise spent details and Loading spinner goes for ever :-(

Any help will be appreciated

**Comment by shridhar-tl** [comment]
Hi @palanid - Have you tried the JQL you provided directly in Jira and ensured if it is working? If not I would suggest to try it once in jira and ensure that it is working fine.

If that doesn't help, then kindly provide the JQL and error log from console. While providing the console error log kindly ensure it doesn't contain any confidential information which you should not share in public forum.

**Comment by saurabhbansal123** [comment]
Issue = IA-1882
I am using this basic jquery, is there anything else which needs to be provided other than issue list? 


Getting the error: "One or more action failed"

**Comment by shridhar-tl** [comment]
Hi @saurabhbansal123 

Yes, your query can be as simple as that and it should work. Please look at the following screenshot where I have used similar simple query and it worked.

Are you sure a jira ticket with key IA-1882 exists in jira. If yes, then please attach console screenshot which would contain additional technical error message which would help me to let you know the exact reason on why it failed.

![image](https://user-images.githubusercontent.com/37339683/126670727-0f66564b-ff29-4480-af7f-50866e1eff76.png)

**Comment by saurabhbansal123** [comment]
My network firewall is blocking uploading any images to github

`The exact error message is "one or more of the actions failed"

Also the ticket exists in Jira and I am able to view the ticket in the Jira assistant dashboard as well as jira filter. It only gives error on this widget. 

Also does the ticket require specific statuses to be used in the widget?

**Comment by shridhar-tl** [comment]
hi @saurabhbansal123 , No such specific restrictions are their. untill the time a ticket exists and you have permission to get the details, this should work. 

I have looked into the code and unfortunately I couldn't guess anything. Some additional information is required for me to analyse what is causing the issue.

It would be very hard to guess anything without the error in console. I understand you were not able to paste the screenshot, but when this error occur, what is being logged in console, other than the action failed message you shared already. Definitely their must be something additional. You can even copy paste the error in console (not in screen) instead of screenshot. Or you can check the network tab and see if api is giving some kind of error.

Even you can copy paste the response of API **(after changing any confidential information)** so that I can look into it and see if difference in api response due to jira version causes trouble.

**Comment by sshandilya** [comment]
The API appears to be mistyped "/rest/api/**3**/project/PROJECT/statuses" 

The "3" should be "2". Changing it manually to "2" works in the browser.

**Comment by saurabhbansal123** [comment]
Hi @sshandilya  
where do i need to make that change?

**Comment by shridhar-tl** [comment]
Hi @saurabhbansal123 @sshandilya  - The issue you reported about Api version has been resolved long back. Hope you would have realized that.

@palanid - I hope this should have solved your issue as well. As there were no activities on this issue since more than an year, I am closing this issue. If anyone else is still facing any issue, please feel free to provide more details and reopen the ticket.
