### ISSUE TITLE
I tried adding more users under default group, but couldn't do so

### ISSUE THREAD

**Issue by BensonAMI** [shridhar-tl/jira-assistant#151]
Hi
<img width="957" alt="JA_Assistant_issue" src="https://user-images.githubusercontent.com/64626610/80781318-7b6f2380-8ba4-11ea-9d8a-859e75f19405.png">

I am exploring your plug-in Jira Assistan v0.97 in JIRA cloud. I tried adding more users under default group, but it doesn't allow me. I keep getting "Action Error" - One or more of the actions failed. Currently, I can only see my name under the group. Am I missing anything here?

Any help will be much appreciated.

**Comment by shridhar-tl** [comment]
Thank you for reporting the issue. Please refer #148 to track the issue details and for workarounds. Closing this issue as it is a duplicate.
