### ISSUE TITLE
How to properly import JIRA issues with labels from CSV?

### ISSUE THREAD

**Issue by pavelsg** [shridhar-tl/jira-assistant#153]
Chrome plugin
I've tried different options (single quotes, double quotes etc.) but whenever I try to import issues with the Label field set to some value (non-empty) JA marks this field as invalid. 
Please advise

**Comment by shridhar-tl** [comment]
This issue has occurred due to a minor validation issue and now that has been resolved. But still whether those labels gets applied to ticket or not depends on whether it is allowed at the time of creation.
