### ISSUE TITLE
Unauthenticated in less than a day though I'm logged in Jira and "Open Jira url" is unresponsive

### ISSUE THREAD

**Issue by aidar-ms** [shridhar-tl/jira-assistant#154]
It's been happening this week. Jira assistant logs out too often and then when I'm logged out, I can't even re-log in because "Open Jira url" button is just unresponsive.

I tried to check browser console to check if there were some obvious JS errors, but didn't find anything.

**Comment by shridhar-tl** [comment]
Is this issue still reproducible? If yes, can you directly access the url of Jira in browser and see if are signed in? If you are signed in then once again access JA and see if it is working.

Also are you using cloud version or self hosted version? Let me know the version number of Jira as well if you are using a self hosted version.
What is the browser you are using and version of the browser.
When you say `"Open Jira url" button is just unresponsive` I am not clear what happens, are you not able to click the button itself as browser is not responding or after clicking Jira is not getting opened?

**Comment by shridhar-tl** [comment]
Hi @aidar-ms - As I haven't heard since long time, I hope this issue is resolved and hence closing this issue. If you are still facing this issue, I would request you to provide the console error details as it should definitely have some information about this error.

**Comment by shridhar-tl** [comment]
Hi All, I hope this issue would have been resolved as part of #214. If anyone is still facing this issue, please provide additional details as mentioned in the ticket.`
