### ISSUE TITLE
Custom report improvement?

### ISSUE THREAD

**Issue by a5066987** [shridhar-tl/jira-assistant#157]
Currently custom report can not display ticket No. and there's no icons like in default my open issue. 

Is it possible to improve this?

**Comment by shridhar-tl** [comment]
@a5066987 Custom report can display ticket number. Select key from the list of fields and it will show the ticket number. I will think about icons and see how simple is it to implement.

**Comment by u3IFw2wfJ** [comment]
@shridhar-tl  I searched a lot of keywords just not "key", thank you!

**Comment by shridhar-tl** [comment]
A all new custom report was being developed and would be available soon for all the users. Based on this report, existing custom report would be deprecated and will be removed soon once this new report becomes stable enough for use.

**Comment by Azzmurr** [comment]
Hi there. I converted all my custom reports from old to new.  New custom reports are better unambiguously. But, there are few issues. First one, I not able to drag and drop column to group data on dashboards, second one, as soon as I tried to move gadgets on the dashboard with new custom reports, app crashed with error in console:

`4.05d0d9fe.chunk.js:2 TypeError: Cannot read property 'settings' of undefined
    at a.value (18.41666616.chunk.js:1)
    at a.value (18.41666616.chunk.js:1)
    at xo (4.05d0d9fe.chunk.js:2)
    at Ra (4.05d0d9fe.chunk.js:2)
    at vs (4.05d0d9fe.chunk.js:2)
    at cu (4.05d0d9fe.chunk.js:2)
    at uu (4.05d0d9fe.chunk.js:2)
    at eu (4.05d0d9fe.chunk.js:2)
    at 4.05d0d9fe.chunk.js:2
    at t.unstable_runWithPriority (4.05d0d9fe.chunk.js:2)`

**Comment by shridhar-tl** [comment]
Hi @Azzmurr - Thank you for reporting this issue. The issue you reported is fixed in version 2.1 and is already published. Once you have the update, it should get resolved.
