### ISSUE TITLE
Can't change value of filed "Open tickets JQL" at Advanced settings

### ISSUE THREAD

**Issue by X-wall** [shridhar-tl/jira-assistant#158]
I can't change value of filed "Open tickets JQL" at Advanced settings - it's uneditable.
I see default value "assignee=currentUser() AND resolution=Unresolved and status != Closed" and want to fix it - how can I do it?
Does it have some restrictions on this field?

**Comment by shridhar-tl** [comment]
You can start typing it and it should work. But don't try to change it under default column. Try to change it for individual instance alone and it will work. Refer the following screenshot. First column (default) cannot be changed, but other columns are editable:

![image](https://user-images.githubusercontent.com/37339683/87944121-9a52c700-cabc-11ea-90ec-fc8961e4b4a8.png)

**Comment by X-wall** [comment]
It's work! Thank you very much!
