### ISSUE TITLE
Closed tickets can be logged against but are not listed

### ISSUE THREAD

**Issue by hardysabs2** [shridhar-tl/jira-assistant#160]
If I turn on the allow to log time on closed tickets and jira allows this, it turns out the ticket can be logged against, but the ticket does not appear in the drop down list.

This is misleading.  Is there a way to resolve this?  Or alternatively make it clearer that the free text ticket name is valid and is being logged against even though it is not in the drop down list.

Additionally can the value after actual selection from the ticket dropdown be made to display all of  what was in the dropdown text list rather than just the ticket ID.

**Comment by shridhar-tl** [comment]
Hi @hardysabs2 - Their are 2 questions in your comment:

1. How to show closed tickets in autocomplete?
Ans:  This is possible by changing the "Ticket suggestions JQL" for your instance from Advanced Settings page. Please refer the following link to know more about individual settings: http://jiraassistant.com/features/settings

2. Showing issue title along with key in drop down.
Ans: This is already being tracked as part of #111. As this implementation will need considerable effort and outcome value is small, will be implemented only if popularity is more.

**Comment by shridhar-tl** [comment]
@hardysabs2 - Assuming my suggestion solved this issue, closing this ticket
