### ISSUE TITLE
Calendar view - context menu (right click on workload) - add "open ticket" to open releated ticket

### ISSUE THREAD

**Issue by SirYasko** [shridhar-tl/jira-assistant#161]
Ticket should be opened on new (browser) tab.

**Comment by shridhar-tl** [comment]
@SirYasko - This suggestion has been implemented a month back and is available for chrome user already. Hope it solves your request. Please verify and confirm.

**Comment by SirYasko** [comment]
Yeah I know it 🥇 and I'm very happy.
