### ISSUE TITLE
Using email as worklogAuthor filter instead of UUID

### ISSUE THREAD

**Issue by drigolin** [shridhar-tl/jira-assistant#164]
As we are using Google as our authentication proxy for atlassian jira cloud instance and JA is using my google email for filter worklogAuthor instead of the UUID. In that way JA doesn't find any worklog for my user but it finds worlogs of other people in the team. 
I have changed my email id and username id into advanced configuration of JA putting my UUID of Jira  but api call still using my email as JQL value for the filter of my tickets.
Any suggestion how to solve that?

**Comment by shridhar-tl** [comment]
@drigolin - Where do you say Worklog is not fetched? If you are primarily worried about Worklog Report, you can try to remove your self and try adding it again and see if it solves. But for other parts of the application like Calendar, at this point it is made to use current logged in user as default which should work. I am not sure what all modules of the application is not pulling your worklog. can you please confirm if none of the modules are pulling the worklog are only specific modules. Like :

Worklog report
Calendar
Gadgets in dashboard
Sprint report
etc.

**Comment by drigolin** [comment]
In any part of the JA where is retrieved my worklogs from jira application
is sending the clause worklogAuthor in ("myemail@mydomain.it") . But this
doesn't work and need to be changed to worklogAuthor in (uuidofmyuser) I
have changed my email Id and user id into advanced panel of JA but
application still using my email. I have tried many times but JA cache or
use email instead of uuid. I'm using jira cloud .

Il gio 3 set 2020, 06:37 Shridhar TL <notifications@github.com> ha scritto:

**Comment by drigolin** [comment]
Removing and adding my name to report and teams doesn't solve. I presume
jira cloud in case of external authentication in gsuite is referencing
users via uuid and not via email. If I use issue filter in jira my email or
name is converted in uuid before sending the query.

Il gio 3 set 2020, 06:37 Shridhar TL <notifications@github.com> ha scritto:

**Comment by drigolin** [comment]
Other option is to user the "currentUser()" function for the logged in user in place of the accountId (what I have called UUID).

**Comment by drigolin** [comment]
Testing 2.1  the problem is fixed in the calendar view as all "currentUser()" worklogs are retrieved.
In case my user is added to a user group for worklog reporting email still sent. Maybe here a check if the email of the user added to the group is equal to the currentUser() email currentUser() can be used in the JQL query.

**Comment by shridhar-tl** [comment]
I am little bit unclear with this issue. Earlier you stated it is working for others in your team. Hope they are also using the same authentication and they should also have their email id being sent to server. Then how could it work for others? I would like to know the root cause for this so that, I can provide better fix. Can you please clarify on following points:

1) I understand, for you Jira is not returning worklog details using email id. But how about others. I hope for them as well same should be the case. How does it work for others?

2) I believe if you add others to your group hope it works for those records. It only doesn't work for your record.

3) Did any of your team members tried to add your name to their group and check if worklog is being returned?

**Comment by drigolin** [comment]
@shridhar-tl  yes is very strange, for me (logged in user) worklog are returned only if worklogAuthor = currentUser() or worklogAuthor = myaccountid (the long uuid code). If I want query other peole's worlog I can use their emails or their account ids. Maybe is a Jira Cloud bug or anomany? At the moment JA v2.1 is able to download my worlogs and other people worklogs. My last note is when I'm added to a user group for reporting the reporting query is filtering using my email and should use my account id or currentUser().
1) for other email is accepted and returns their worklogs.
2) Correct.
3) I have asked to do the test, tomorrow I will let you know.

**Comment by shridhar-tl** [comment]
@drigolin - Any update on this?

**Comment by drigolin** [comment]
My collegues don't see my worklogs. It seems that only worlogs on ServiceDesk are reported but all worklogs on Jira aren't visible id filtered via my email. Maybe is because I'm the site admin of the cloud installation? It seems that my account has a special behaviour. My collegues are able to see their own worklogs with no problems at all. But I confirm that they cannot see all my worklogs.

**Comment by drigolin** [comment]
After testing I confirm that is working correctly
