### ISSUE TITLE
"Add Worklog" Button in "Ticketwise Worklog" does not work

### ISSUE THREAD

**Issue by eikooo** [shridhar-tl/jira-assistant#165]
When clicking "Add Worklog" (after right click on a ticket number) in the "Ticketwise Worklog" view, nothing happens. 

Browser: Firefox 80.0.1
Jira Assistant Version: 1.6

**Comment by shridhar-tl** [comment]
@eikooo - Closing this ticket hoping this issues is resolved. If you still face this issue, please re-open this ticket.
