### ISSUE TITLE
Firefox - is not opening after latest 2.1 update

### ISSUE THREAD

**Issue by DenysOd** [shridhar-tl/jira-assistant#166]
Extension is not opening in Firefox after latest update
Firefox 80.0.1 (64-bit)
Ubuntu 16.04 - Ubuntu 4.15.0-118.119~16.04.1-generic 4.15.18

**Comment by shridhar-tl** [comment]
It works well with windows and unfortunately, I do not have any system except Windows to test it. Can you please provide more details on what is the behaviour you are observing? Are you seeing the menu when you click on JA icon or not?

Can you try to access following urls and see if it loads properly. Also see if their are any errors in console:

1. moz-extension://5289744f-3a44-4931-8c86-c6e8acd616fa/index.html
2. moz-extension://5289744f-3a44-4931-8c86-c6e8acd616fa/menu.html

**Comment by DenysOd** [comment]
1. I can see Menu but clicking on its points does not have any reactions
2. Provided URL are not opening
3. Any console error are present

Note: After Executing mentioned above steps - I got access Assistant at address moz-extension://9073d4e8-93f0-40c6-b4db-7f6300e6c674/index.html#/2/dashboard/0  

So basically you can close this defect - look like local troubles 
Thanks in advance

**Comment by shridhar-tl** [comment]
Based on your confirmation, closing this issue. Please feel free to reopen this ticket if you continue to face this issue again.
