### ISSUE TITLE
Wrong dates are displayed in Work log for "this week" selection?

### ISSUE THREAD

**Issue by richcbaker** [shridhar-tl/jira-assistant#167]
Wrong dates are displayed in Work log for "this week" selection?

![image](https://user-images.githubusercontent.com/4889648/94442218-9b2e6600-019b-11eb-805e-a1fed46c9c13.png)

Thanks
Richard

**Comment by richcbaker** [comment]
Bizarrely it is now correct!

**Comment by shridhar-tl** [comment]
Week selection works based on Start of Week settings from General Settings page. Select the Start of Week as Sunday or Monday as needed and the same will reflect throughout the application.
