### ISSUE TITLE
Logging work on closed issues

### ISSUE THREAD

**Issue by piranha79** [shridhar-tl/jira-assistant#171]
I stumbled upon the fact that JA doesn't allow to log work on closed issues while JIRA (at least as of v8.4.1) is totally ok with such work logs. I wonder whether this has been a restriction formerly enforced by JIRA or it is a constraint JA did put up. I'm aware of the fact that post-hoc logging work on already closed tickets is a bad practice but somehow can't get rid of the lazy guy in me. 😉

**Comment by shridhar-tl** [comment]
Hi @piranha79 - You can enable logging work on closed tickets from General Settings -> Worklog tab as shown in the following screenshot. Assuming this would solve your issue and closing this ticket.  Feel free to reopen this ticket if you are expecting something else.

![image](https://user-images.githubusercontent.com/37339683/97951204-6c6d6600-1dbf-11eb-83f0-309f22c8aa39.png)

**Comment by piranha79** [comment]
@shridhar-tl oh boy I'm an idiot and you totally rock! Thanks for your perfect response and my apologies for the fact that I didn't check the settings before filing useless issues.
