### ISSUE TITLE
Can't logout from the project 

### ISSUE THREAD

**Issue by topicaulp** [shridhar-tl/jira-assistant#172]
Hi, 

I can't find how I can log out of the Jira project.

I have several Jira projects on Jira Assistant and I need to remove a couple of them. 

Thanks.

**Comment by shridhar-tl** [comment]
Jira Assistant v2.32 has option to remove the unwanted accounts in Advanced Settings page.

![image](https://user-images.githubusercontent.com/37339683/135870140-8e2f9a2e-ef62-4bb8-b1da-a0350f5f659c.png)

Closing this ticket assuming this solves your issue. Please feel free to reopen this ticket if things are not working as expected. thank you.
