### ISSUE TITLE
HTTP/400 answer from Jira ignored while creating worklog entry

### ISSUE THREAD

**Issue by mlouiset** [shridhar-tl/jira-assistant#175]
Hi,
First, thank you for this great extension! makes my life much easier 👍 

Here is my concern:
On a (cloud) Jira Project I changed the configuration to prevent users from creating work log entries on Epics. I did this: 
https://community.atlassian.com/t5/Jira-questions/Disable-quot-Log-work-quot-on-EPIC/qaq-p/610394#M410540
As a consequence, Jira now answers with a HTTP/400 response while attempting to create a work-log entry on an Epic. But JiraAssistant seems to ignore it.
![image](https://user-images.githubusercontent.com/6031222/100268416-4ddd3380-2f55-11eb-9969-3bb30e6b02ca.png)

Steps to reproduce:
- Add a new work-log entry on an Epic from the calendar view
- reload the page (Shift+F5)

Actual Behaviour:
While adding the work-log entry, the "Add worklog" window stay opened, and no worklog in the calendar view
While reloading the page, I can see the work-log entry in the calendar view, but not sync (marked as to be uploaded, which always fails)

Expected Behaviour:
display the error message returned by Jira in a pop-up window(?)

Best regards

**Comment by shridhar-tl** [comment]
Hi @mlouiset , Thank you for reporting this issue. This issue has been resolved in various modules and is already published in Web version of JA. It would be published for extension and Cloud App users in next couple of days.

This fix is ready for you to have a look at Web version. Closing this ticket considering your issue resolved. If you still face any issues, please feel free to reopen this ticket
