### ISSUE TITLE
Worklog with ic time

### ISSUE THREAD

**Issue by Vaelek** [shridhar-tl/jira-assistant#179]
My employer has configured IC Time to handle worklogs. There is a required "Action" field that I cannot set from JA. The Activity selection does not populate within Jira itself unless a ticket number is present. Any way to make this play nicely? Currently it's just blank on anything uploaded from JA.

![image](https://user-images.githubusercontent.com/293765/103443216-82ae6b80-4c22-11eb-8d2e-50b04d51f591.png)

**Comment by shridhar-tl** [comment]
As mentioned in #237, these fields are external to Jira and Jira API does not support pushing the value to Jira. Hence this implementation becomes out of scope for Jira Assistant.

Have a look at the comment in #237 to know more about it.
