### ISSUE TITLE
Improvement: Allow to define default time period for worklog report

### ISSUE THREAD

**Issue by psalkowski** [shridhar-tl/jira-assistant#184]
It would be nice to have the ability to set the default time period for worklog report. We can use predefined options from the date picker like:
- This month
- Last one month
- Last month
- This week
- Last one week
- Last week

**Comment by mulawamichal** [comment]
and store it to be loaded for future usages (so that when user clicks "worklog report" from the menu it will load the previouly used timerange and load the report).

**Comment by shridhar-tl** [comment]
Hi @psalkowski @mulawamichal , This implementation has been done long back as part of different ticket. The data would be prefilled with the previously selected dates. However, data would not be automatically pulled as data could be huge and hence users are expected to click on the refresh button to load the data.

I am considering this as implemented and closing this issue. Please feel free to reopen this issue if something does not feel right.
