### ISSUE TITLE
Allow all sprint issues in Worklog Report

### ISSUE THREAD

**Issue by kylehoare** [shridhar-tl/jira-assistant#186]
In a Worklog Report, it would be nice to be able to add issues regardless of weather work has been done on them. 

Use case:
I use this with our weekly meetings and use it to get what issues each user has been working on and also issues they will be working on next. currently the latter is not possible

**Comment by shridhar-tl** [comment]
Hi @kylehoare, Already sprint report does the same. Your sprint report contains a worklog section where all the issues are listed and worklog would be shown for indivudual users.

**Comment by kylehoare** [comment]
Hi @shridhar-tl, true but the work report has the grouped tab which is an awesome view.

**Comment by shridhar-tl** [comment]
Worklog report is designed to show worklog information and it is grouped based on user. Hence with the way how it is built makes it difficult to do such implementation. Closing this issue as of now and later if I see the possibility, will rethink about it.
