### ISSUE TITLE
How to extract worklog comments across tasks

### ISSUE THREAD

**Issue by dana95858** [shridhar-tl/jira-assistant#187]
Hello, 

Can you please advise if Jira assistant would provide an option to extract work log comments across different tasks for each employee - to get a report similar to this: 
![image](https://user-images.githubusercontent.com/77169950/117882518-b96c5080-b2aa-11eb-84fd-105a3a23b5b1.png)

Please advise. 

Thank you in advance.

**Comment by shridhar-tl** [comment]
Hi @dana95858 , I hope worklog report should meet your needs. Generate worklog report for the time period and go to the Flat (Groupable) tab of the report. It contains individual worklog entry along with comments column. You can show or hide any fields as per your needs.

![image](https://user-images.githubusercontent.com/37339683/119763739-b6d64180-becd-11eb-8a2d-cccfe43a0219.png)

Hope this helps. If their are any more queries please feel free to reachout to me.

**Comment by dana95858** [comment]
Hi, @shridhar-tl Thank you very much. 
You have been very helpful.
