### ISSUE TITLE
Sometimes after publishing changes are not available in live

### ISSUE THREAD

**Issue by dana95858** [shridhar-tl/jira-assistant#190]
Sometimes after publishing changes are not available in live. We have to delete the bin and re-publish to fix the issue, when we check the box Delete every time and publish but it takes too long.

So someone from IT department has to manually delete the bin folder and publish to fix the issue.

This happens for both javascript changes or code changes. This often happens for User controls.

Please advise how do we fix this.

Thank you in advance. 

![bin](https://user-images.githubusercontent.com/77169950/119724551-223cf680-be6f-11eb-98dd-e5ae45203560.png)

**Comment by shridhar-tl** [comment]
Hi @dana95858 , Sorry, but I am totally unclear on what you are talking about. What you are publishing and what is unavailable. I am not even sure about what you mean by bin, box and the screenshot you sent.

Please provide some more details.

**Comment by dana95858** [comment]
Hi @shridhar-tl  
My apologies, I think I added my question to the wrong category. 
Thank you.
