### ISSUE TITLE
Updating My Open Tickets Gadget does not update pointers for worklogs generated from the gadget.

### ISSUE THREAD

**Issue by smchowdhury** [shridhar-tl/jira-assistant#191]
Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)
JA v2.31

If a user resolves a Jira ticket, then refreshes the My Open Tickets gadget to update their list, worklogs generated through the gadget still point to the pre-refresh ticket list.  A full refresh of the page properly updates the associations.

1. User resolves DB-8826, which was the first item in the gadget list.
2. User refreshes the My Open Tickets gadget, which now lists DB-8830 as the first ticket.
3. User generates a worklog for DB-8830 through the gadget.
4. The worklog generation modal appropriately lists DB-8830.
5. After confirming the worklog creation, the Worklog Pending Upload modal updates with the new worklog, but points to DB-8826.
![image](https://user-images.githubusercontent.com/8026821/123658528-cfed4d80-d7ff-11eb-96bb-a2653e564f42.png)

**Comment by shridhar-tl** [comment]
Hi @smchowdhury,  Thank you for reporting this issue. This issue has been resolved and would be available by next week in upcomming release.
