### ISSUE TITLE
Incompatibility with multi account container

### ISSUE THREAD

**Issue by ZeeD** [shridhar-tl/jira-assistant#194]
Hi.
I'm using firefox with [firefox's multi account container plugin](https://addons.mozilla.org/it/firefox/addon/multi-account-containers/)
and I am logged in jira in a "work" container.
The jira assistant plugin couldn't "integrate" with the jira server. I needed to *also* login in a new (non container) tab to allow the plugin to work.

**Comment by shridhar-tl** [comment]
Duplicate of #103
