### ISSUE TITLE
Getting error when running the work log report post the automatic upgrade

### ISSUE THREAD

**Issue by sagar-bhate** [shridhar-tl/jira-assistant#197]
Since the time the plug in has upgraded i am getting the below error when opening the dash board.
![image](https://user-images.githubusercontent.com/91881500/135833678-a8654037-2ba7-4745-9a52-ed93e7706202.png)

Also i am not able to run the work log report. It says that Javascript must be enabled in the browser. I have checked and can confirm that Javascript is enabled.

**Comment by shridhar-tl** [comment]
Hi @sagar-bhate - This issue is already being answered in #196 . Check my response in #196 to solve this issue.

Hence marking this as duplicate and closing this issue.
