### ISSUE TITLE
Custom report expressions are not processed correctly

### ISSUE THREAD

**Issue by over1pixel** [shridhar-tl/jira-assistant#199]
I mean, I couldn't find any documentation or any example to compare with, but any expression I put in the box is not processed when accessing worklog data.
If I put, for example, "this" keywork, in the column I can read the Json of the current object, but there I cannot extract any fields value if I refer to any property.

My intent was to extract the "worklog.updated" field in the report, but every attempt result in empty cells

**Comment by shridhar-tl** [comment]
Multiple fixes has been done in expressions and now documentation is also available online explaining how to use expressions. Hence closing this issue.
