### ISSUE TITLE
Firefox version of extension was disabled after the latest release of Firefox

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#20]
After the latest version of Firefox is released, for some users the extension is automatically disabled / removed.

**Solution:**
If the extension is disabled you can enable it again from the "Add-ons" menu in Firefox. If it is removed, then you will have to install it again from the following URL: https://addons.mozilla.org/en-US/firefox/addon/jira-assistant/

But unfortunately, in store as well it is disabled. So till new version is uploaded again to Firefox addons store, their is no way around this to use in Firefox. I assume a new version will be available for Firefox in a couple of weeks from the date of this issue being raised.

**Comment by shridhar-tl** [comment]
This issue has been resolved and now Firefox version is again available for use. Hence closing this ticket.

**Comment by TISindiaSupport** [comment]
same problem again

**Comment by shridhar-tl** [comment]
Hi @TISindiaSupport ,
Jira Assistant will not be available in Firefox Addon store anymore. You have an alternate for this from the issue #43 .

You can find the download link for Firefox version from the below url: https://github.com/shridhar-tl/jira-assistant

**Comment by shridhar-tl** [comment]
Jira Assistant is once again available in Firefox addon store since long time now.
