### ISSUE TITLE
date picker not properly pushed down

### ISSUE THREAD

**Issue by alainbelez** [shridhar-tl/jira-assistant#200]
i am currently trying to pin the window on the side of my monitor, but when window got a bit small, date picker is not properly pushed down, causing the calendar to not show properly.

![image](https://user-images.githubusercontent.com/6648110/139961871-47c51d1b-13b1-4176-b52a-7c60214554d9.png)

easy solution is to add a clear fix after the gadget-header.

![image](https://user-images.githubusercontent.com/6648110/139962022-1ee7278a-2146-457d-959d-6987d71eee5b.png)

can you help fix?

**Comment by shridhar-tl** [comment]
Hi @alainbelez Thank you for reporting this issue along with a solution. Fix has been added and would be available after next publish.
