### ISSUE TITLE
Hosted web version of jira-assistant

### ISSUE THREAD

**Issue by jycr** [shridhar-tl/jira-assistant#201]
We like to host this application on our same server that currently hosts our Jira Data-center instance.
Is it possible to create a "web app" version that it can be deployed on Apache HTTP server?

**Comment by shridhar-tl** [comment]
Hi @jycr , This app is developed using React only and so it is just a static website. But still, this doesn't have any authentication logc with Jira. Currently it uses browsers authentication by default which is supported only if it is an extension.

If this is hosted as a web site in any server, then current authentication logic won't work and needs code changes for it to be working. By the way, their are few more additional capabilities which is specific to a browser extension. Those features has to be removed / hidden.

With some code changes, it is definitely possible to host it as a website in any server. Please feel free to fork the branch and make required changes. If you have any queries, please contact me via mail for quicker response.

**Comment by shridhar-tl** [comment]
Closing this issue as their were no further comments. Please feel free if their are any more questions.

**Comment by shridhar-tl** [comment]
Hi @jycr - As part of #221, this extension is rearchitectured to be hosted as a web application as well in any server. Additionally for authentication, OAuth2 is implimented for Cloud version of Jira. As of now, when run as website it does not support authenticating with self hosted version of Jira which is your case.

So as of now all the work required for this tool to be hosted as web app is done. But few more changes would be required to integrate it with your self hosted version of jira and authenticate. If you are still looking for option to host it in your datacenter, please contact me via mail with all the required details and I will see if I can help to get it done.

I had infact already hosted it as static site in https://app.jiraassistant.com (using GitHub Pages). This is primarily for beta testing the upcomming changes by integrating with Chrome extension, but additionally have the capability to work standalone using OAuth 2 based integration with Jira Cloud.
