### ISSUE TITLE
Import from cycle numbers in worklog, don't work as expected

### ISSUE THREAD

**Issue by sreher** [shridhar-tl/jira-assistant#208]
Hello, 

i have the following issue. I exported worklogs from an other system and have problems to import this numbers. More than 2 fractional digits are not allow. 

```
Ticket No;Start Date;Timespent;Comment
OUT-728;2021-10-01;0.33333333333333;Daily   
OUT-728;2021-10-01;1.6666666666667;Daily   
OUT-728;2021-10-01;0.83333333333333;Daily   
OUT-728;2021-10-01;1.4166666666667;Daily   
OUT-728;2021-10-01;1.0833333333333;Daily   
```

Result: 
![image](https://user-images.githubusercontent.com/302229/154159725-24bc0380-1165-4517-84a6-ac68ffb4fa89.png)

If I reduce the 0.33333333333333 to 0.33 than the result is 

![image](https://user-images.githubusercontent.com/302229/154160282-18fbee31-4397-4dfc-bf5e-1ada193771d6.png)

I want to import the worklog in this manner:

![image](https://user-images.githubusercontent.com/302229/154160732-5d692d35-b7a4-4456-b09c-04b577528325.png)

How to handle this issue without to manipulate the export again?

Thanks for your help and this cool plugin.

**Comment by shridhar-tl** [comment]
Hoping this issue is already resolved and closing it. Please feel free to reopen it if you still face this issue.
