### ISSUE TITLE
Date picker: too easy to dismiss and lose changes

### ISSUE THREAD

**Issue by johnbeard** [shridhar-tl/jira-assistant#211]
When changing the date of an issue in the calendar, it's too easy to dismiss the dialog by de-focusing the picker. This will discard the date you have selected (i.e. clicking outside the picker and clicking "cancel" are equivalent). Because very many date pickers forms like this update immediately, without an Apply button, it's extremely common to then lose the new date.

Also the apply button is not obviously part of the picker as it's below the calendar area, whereas the affordance to open the picker is _above_ the dialog and the dialog border is very light so the "apply/cancel" toolbar fades into the background dialog:

![2022-06-06-122423_3840x1080_scrot](https://user-images.githubusercontent.com/5386578/172153022-ecf37900-b24e-437d-bdde-18635b580351.png)

I suggest that either the picker becomes "update on select" (like, say, the ones on Jira) or do not allow to dismiss the dialog on defocus if there are changes (i.e. make the user deliberately select "cancel" or "accept").

**Comment by shridhar-tl** [comment]
Hi @johnbeard - Thank you for your suggestion. But unfortunately the date picker component which is used does not support such capablity. I have already tried workarounds by trying to intercept the close events and set the selected date long back and that too doesn't work as expected.

Alternatively, you can post this query in actual date picket component (link provided below) and if they can provide support for this feature, I am happy to implement it.

Date picker Component: https://www.daterangepicker.com/#options

So as of now it is not possible to implement this functionality and hence closing this ticket. But please feel free to reopen this ticket if you know of any other possibility.
