### ISSUE TITLE
Calendar view remains white in dark theme

### ISSUE THREAD

**Issue by jeed2424** [shridhar-tl/jira-assistant#215]
In the previous versions, the dark theme would render the calendar view black (or dark gray) but as of v2.37, the calendar view remains white regardless of the theme used.

**Comment by shridhar-tl** [comment]
@jeed2424 - This issue has been resolved and is already available in Web version of JA. You would start seeing this change in extension after you are upgraded to JA v2.44.

Hance closing this issue considering it is resolved
