### ISSUE TITLE
Screen stuck on Loading.....Please wait screen. 

### ISSUE THREAD

**Issue by brandonsbuckner** [shridhar-tl/jira-assistant#22]
When opening Jira Assistant (installed yesterday), there appears to be a message in the top right corner, but no message is shown. Also, the Loading... Please wait... has been there for over 10 minutes. 
[JA.docx](https://github.com/shridhar-tl/jira-assistant/files/1971029/JA.docx)

**Comment by shridhar-tl** [comment]
Thank you for letting me know about this issue. Please check the browser console once and let me know the error message displayed in the console.

Also it could be related to  #18. Go throught #18 and see if your issue gets resolved. If not please add additional details to this ticket from console output. Thank you.

**Comment by shridhar-tl** [comment]
Hi, Please let me know if this issue is resolved or not.

**Comment by brandonsbuckner** [comment]
Shridhar,

Sorry for the delayed response. I was unable to recreate, I just removed and erased the extension and have not seen the issue again. 

Brandon

**Comment by shridhar-tl** [comment]
Ok @brandonsbuckner, then I will consider this issues as resolved. In case if you feel this issue again or face some other issue, please check the console for any errors. And as mentioned in #18 you should have sufficient free space in C <drive> as well.

Thank you for your update!
