### ISSUE TITLE
Add a timer or stopwatch to track working on a ticket and log hours

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#222]
I get few requests on adding a timer / stopwatch for worklog creation. This has been already part of Jira Assistant until early 2017, but was later removed as part of major rewrite. This is due to the fact that it's not being used by anyone based on Google Analytics data.

If any of you feel this would be a useful feature, please +1 or leave your comments on how this can be implemented.

I need suggestions from users on how to track this. I could think of some of the use cases where I think tracking worklog would be difficult from a browser extensions perspective:
- User starting the timer on one issue and working on multiple tickets simultaneously
- User having the timer running, but in between, they attends few meetings which should not actually be captured as part of this story
- Timer running for more than one day. There is no way a browser extension can identify when user logs in and sign off from his work. 

Please provide some suggestions on what could be useful and based on that I will try and prioritize this work.

**Comment by casper-81** [comment]
Used a similar time tracking tool a few years ago:
- User can choose only one issue to start tracking. Can be a right click on a issue -> Start Tracking.
- A popup could be shown to the user, kind of "Tracking time for issue ABC-12345".
- This popup can have 2 buttons/links: Pause Tracking and Stop Tracking.
- If Pause is selected, user can anwser a phone call or whatever, and then he can have 2 buttons/links:  Resume Tracking or Stop Tracking.
- If Resume is selected, show goes on.
- If Stop is selected, then a worklog is added to the Pending Upload List. User can change or adjust total time tracked by editing the worked log.
- To prevent all-night-long recording, there can be a auto stop protection. Lets say if user (browser activity) is inactive for 15 minutes, Time Tracking is stopped automatically and a worklog is added to the Pending Upload list.  Time for inactivity could also be configurated somewhere in Settings -> General.

Cheers m8 :)

**Comment by shridhar-tl** [comment]
Hi, I am working on this feature and here is the screenshot of the initial implementation. Initial working version would be available in Web version by this week end.

![image](https://user-images.githubusercontent.com/37339683/183957451-79b5b5bb-560f-4068-93e7-73723ecac4ab.png)

Any suggestions on design or functionality is welcome.

**Comment by shridhar-tl** [comment]
Hi @casper-81 - This feature is now available in Web version and would be published to extensions soon. As of now you can test it in Web version by access https://app.jiraassistant.com.

As of now, Web version supports starting a timer on a particular Jira Ticket, pause and stop it when needed. Once stopped worklog entry would get created automatically and would be displayed in pending uploads gadget and in worklog calendar for you to upload.
Additional settings provided to automatically pause + resume the timer when system is locked or turns idle. This feature is not supported in Web unless extension v2.41 or above is installed. That way, only once the extension is updated you would be able to use this configuration.

Anyway additional features would be added this weekend.

**Comment by casper-81** [comment]
Hi [shridhar-tl](https://github.com/shridhar-tl)

Awesome!

Time tracking is working fine. Done some small tests and everything is working great :)

Under the issue itselft its ok:
![image](https://user-images.githubusercontent.com/110611435/185191625-878934cd-872b-448b-8984-224f6eaec5c8.png)

Just can't see the Play/pause/stop buttons under the board. Not sure if i'm missing some configuration on the board..

![image](https://user-images.githubusercontent.com/110611435/185191459-c1e2592b-4e83-4d53-923d-6cebd2741404.png)

This is the config:

![image](https://user-images.githubusercontent.com/110611435/185191912-6c2f0dcc-4f50-482f-9499-2406f96c751b.png)


Cheers m8 :)

**Comment by shridhar-tl** [comment]
Hi @casper-81 , thank you for the confirmation. In board you need not do anything specifically. It should automatically work. You can just try to increase the delay attaching config up to 4 seconds in the configuration and see if that fixes the issue. If not I would like to know what is the version of Jira you are using. So that I will have to check with that version of Jira and see if the structure of board is different and will have to make appropriate changes.

Stay tuned. More features coming your way !!

**Comment by casper-81** [comment]
Hi @shridhar-tl ,

Its kinda weird. Default value is 2 sec.

If I type 4 and press enter or click somewhere, its doesn't fix the value and change it back to 2:
![image](https://user-images.githubusercontent.com/110611435/185584630-5108c200-43cb-45b7-ba48-d5fa4bd1762e.png)


If I type 04 or 10 sec, it assumes the value but still can't see play/stop buttons under the jira board.
![image](https://user-images.githubusercontent.com/110611435/185585238-0d073cbb-e363-4344-a739-92253da6b2f2.png)


I'm currently using:
- Firefox 103.0.2 (64-bit)
- Jira v8.20.7

Done a browser cache cleanup but didn't help.

Cheers !

**Comment by novosirj** [comment]
I really appreciate this enhancement so much; I didn't think to ask for it, but it's really annoying to be figuring all the time (huh, I started working on this at 3:24, how long has it been since 3:24, etc.). 

One question though: so I track this time, I hit stop when I'm done, and the work log goes into the pending uploads. Where do I upload that to edit the worklog to say what I did, etc. before it's uploaded? I can go in and edit it after the fact, but I'm guessing that's not the best/intended way.

**Comment by casper-81** [comment]
Hi @shridhar-tl ,

Well, maybe you can bring the Add worklog dialog after the Stop button:
![image](https://user-images.githubusercontent.com/110611435/190797656-8e652cd0-1a0c-4ae3-a3e8-ddfc766f2622.png)

So, it will be:
- Start tracking
- Stop tracking
- Bring the dialog. User can add worklog comment or adjust Actual time spent. Log time will be the start of the tracking (Hit Start button), Ticket is the selected ticket of the recording.
- Save button will have actual behaviour (save it to pending upload or directly to Jira).

Cheers m8 :)

**Comment by SuperbananaNL** [comment]
![img](https://user-images.githubusercontent.com/57645866/197790726-aed22f8b-ea4e-4e69-a05f-e1fc8999e568.PNG)
I tried clearing browser cache and setting the attach time to 5 seconds and even up to 20s just to be sure.
However i still only get the time tracker on 1 board.

I do however see manually logged hours of both boards so i suppose the conneciton to the boards should be alright

i am currently using:
chrome: 106.0.5249.119
jira is a cloud based version and im not sure if i can get a version number for that?

**Comment by shridhar-tl** [comment]
Hi @novosirj,
My initial thoughts/assumption was once you start working on a task or any time later, you can provide the comments on what you are working on by clicking on the Edit icon in the timer. This option is currently not available from within Jira. But I am still thinking about it and trying to figure out a way to have it within Jira as well.

![image](https://user-images.githubusercontent.com/37339683/199163619-9c354e94-9c31-42f5-9ae0-e800c99d8ba1.png)

 @BasGrtjns - I have came across such issues from various organizations and reason for this is version of Jira and different styles / customizations done by admins. That is causing JA to not identify appropriate cards in some cases. Once again I am trying various options to achieve consistency. Will keep you posted if there are any progress on this.

@casper-81, Your suggestion to bring edit dialog would be implemented based on configuration. However it would take some more time for these implementations as currently I am more focused on developing automation suit to aid me in regression testing at the time of each release as doing manual regression testing is taking most of my time for every release.

**Comment by konnton** [comment]
What I would like to see is for the timer to kick in as soon as a ticket goes to In Progress, is assigned to someone,  and only track the time during working hours.

**Comment by Equbuxu** [comment]
Big thanks to whoever fixed the issue with the timer functionality not getting attached to the page in the latest update. It finally works well now, and before that I had to restart the extension like 10 times per day to get the timer to appear.

I have a feature request, for the popup saying "timer is already running for ... do you want to stop it and start a new timer". It would be great if the popup also had a text field for a worklog comment (you can use [the prompt() function](https://www.w3schools.com/jsref/met_win_prompt.asp)). I tend to forget to open the app right away to write down the things I've done, and I by the time I notice in the evening I usually half-forget what I was doing, so having it in jira would be great.

**Comment by shridhar-tl** [comment]
@Equbuxu - Your suggestion about capturing comment is taken and will try to accommodate in upcoming release.

About your previous issue, there were no fixes in any recent versions of JA for timer. Infact it is untouched since the time it is published. So something would have changed in your end so that the issue has been resolved now. However, happy to hear, the issue you were facing is resolved.

**Comment by Equbuxu** [comment]
Interesting, I thought I saw a couple of commits related to the timer, guess that was something different. Changes on my end are totally possible, now I should hope that it doesn't break again lol

**Comment by shridhar-tl** [comment]
Closing this ticket assuming this issue is resolved. Please feel free to reopen if there are still some issues yet to be addressed.
