### ISSUE TITLE
Dark mode: right click show a blank menu option

### ISSUE THREAD

**Issue by casper-81** [shridhar-tl/jira-assistant#223]
Hi there!

Using V2.39 on Firefox.

There's a small issue when using dark mode. If u right click on a issue or on a day to add a worklog, you will have a blank menu:

![2022-08-04_14h00_46](https://user-images.githubusercontent.com/110611435/182853589-52233798-81ee-4e0e-a437-6c0d0200e98e.png)

Options will only be showed if you mouse over that menu:

![2022-08-04_14h04_00](https://user-images.githubusercontent.com/110611435/182853816-f67fd8d3-1d31-4ab8-9817-5e8e2b9b5696.png)

Cheers and congrats for this GREAT and AWESOME plugin :D

**Comment by shridhar-tl** [comment]
@casper-81 - This issue has been resolved in JA v2.44. This is already available in web version and would be soon available in extensions in around a weeks time.
