### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by BorisB** [shridhar-tl/jira-assistant#224]
Steps to reproduce:
1. Click extension button on jira page.
2. OR click extension button on other page and enter jira account url and click Integrate.
Expected: see extension menu.
Actual result: Error "One or more of the actions failed" is displayed instead.

Microsoft Windows 11 
Microsoft Edge 103.0.1264.77
Other extensions are disabled.

**Comment by shridhar-tl** [comment]
Can you see if their are console error? Additionally, Edge is currently having v2.36, but already v2.39 is published and is currently being reviewed by store review team. For Edge, I expect the review to be completed within another 3 working days, while for Firefox it is already done and for Chrome I expect it to happen by Monday.

**Comment by shridhar-tl** [comment]
Are you still facing this issue @BorisB? If yes, please provide additional details as requested above.

Additionally, error messages are improved in Jira Assistant v2.41. So once latest version is published, you may start seeing more appropriate / technical error messages which may help in resolving the issue.

**Comment by shridhar-tl** [comment]
As there are no updates in this issue, I believe this issue has been resolved and closing it. Please feel free to reopen this issue with all the required details if you face it again.
