### ISSUE TITLE
Customize WorkLog with additional Fields

### ISSUE THREAD

**Issue by MaeChr** [shridhar-tl/jira-assistant#225]
In JIRA Tempo it is possible to add Fields which are mandatory.
In Worklog this mandatory fields are not accessible so it is necessary to switch to jira and edit the logged work.

So if in Worklog it is possible to add JIRA - Tempo fields so that the mandatroy fields can be filled out.

**Comment by nightscape** [comment]
@MaeChr did you find a solution? I also need to set a custom Tempo field when creating worklogs and need to switch to the JIRA Tempo in order to do that.
Is there a workaround?

**Comment by shridhar-tl** [comment]
No @nightscape, fields added in tempo cannot be provided from Jira Assistant. At least at that time when I did the analysis there are no options.

My extension just integrates with Jira and so it can extend only Jira's functionality. Moreover, tempo is a paid plugin. I won't be able to add functionalities integrating with Temp.
