### ISSUE TITLE
Save date range in Worklog report

### ISSUE THREAD

**Issue by Matysh** [shridhar-tl/jira-assistant#228]
Please add ability to save configuration on screen "Worklog report" to avoid to set the date range every page openings.

**Comment by shridhar-tl** [comment]
This is duplicate of #8. How ever this is implemented and is already available in Web version. Same would be published and would be available for extension users as part of Jira Assist v2.42.

**Comment by shridhar-tl** [comment]
Jira Assist v2.42 is already published and this fix is available now. Hence closing this issue.
