### ISSUE TITLE
Export worklogs to CalDAV server

### ISSUE THREAD

**Issue by quenbyako** [shridhar-tl/jira-assistant#229]
#### Before-begin checklist

- [x] I are already using latest version of Jira Assistant and Browser.
- [x] I verified, that there are no any similar suggestion already requested by others?
- [x] I already saw FAQ at https://www.jiraassistant.com and didn't find any solution for my problem

#### Is your feature request related to a problem? Please describe.

I wanted to see my wrok logs in my macos calendar, and in google calendar, and in todoist, and, idk, everywhere... to plan my work. Unfortunately, only one way i can do it, is an export to csv -> use custom script to convert into ical files, and export them into calendar, which is sooooooooo hard... 

#### Describe the solution you'd like

Create custom self-hosted server, which will work with Jira Assistant to fetch work logs each 5-10 minutes. This is quite hard to implement, but here are the benefits: 1) no need to open jira assistant for exporting 2) no need to think about it, it will work out of the box.

#### Describe alternatives you've considered

Create worklog export to caldav url. It is the easiest way, but still not so useful

#### More information

I can actually create golang caldav server, but i completely not understand, how to integrate it with jira assistant. I have some stuff done already for atlassian api, but obviously, jira assistant provides more features with easier interface. so in my perspective, i think it's better to combine, than make custom app.

**Comment by shridhar-tl** [comment]
@quenbyako - Jira Assistant is just representing the data from Jira and its not the source of data. Moreover if such a server is to be implemented, that has to be a separate application all to gather and is no where related to Jira Assistant. Additionally such a server need not be integrated with Jira Assistant in any way.

Jira Assistant reads and writes data back to Jira only. So if you implement a caldav server to read data from Jira, then it would automatically work as expected. I have thought a lot and I really fail to understand how is Jira Assistant any way coming in between this process except the fact that data is initially created by JA and pushed back to Jira.

If you think my understanding is wrong, please provide more details on my query.

**Comment by shridhar-tl** [comment]
I am closing this ticket for now considering this as nonrelevant to current model. If you have any suggestions, please feel free to reopen it.
