### ISSUE TITLE
Add Recurring WorkLog

### ISSUE THREAD

**Issue by relkcaminc** [shridhar-tl/jira-assistant#23]
As a jira-assistant user, I want to set up a recurring worklog for items such as daily meetings on week days.

**Comment by shridhar-tl** [comment]
Actually the initial version of Jira Assistant had the option of recurring worklog. But later it was removed as that feature is not used by anyone including my team.

This feature will be implemented again if this ticket gets pupularity. If anyone would like this feature to be implemented then +1 this ticket.

**Comment by shridhar-tl** [comment]
Closing this ticket as I do not see any activity in it since long time.
