### ISSUE TITLE
Inbuilt Planning poker to support collabration

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#230]
A new planning poker module has to be added with following capabilities:

1. Support to pick stories to be estimated
2. Invite team members by sharing url / room id.
3. Once estimated, automatically update story points in Jira

This would be first module in Jira Assistant which supports collaboration across users.

**Comment by RyanPoulier** [comment]
Hi, it looks like the search may need some finetuning as most of the tickets I'm searching for don't show up. One example below.

![image](https://user-images.githubusercontent.com/20705927/193795013-75903dc0-947e-4f69-b48e-d955d577cf99.png)

**Comment by shridhar-tl** [comment]
@RyanPoulier - The issue reported about issue picker has been resolved. While it is already available in Web version, you would see the updates in extension once you JA updates to v2.44. Hence considering this ticket as done and closing it. Please feel free to reopen it if you still see any issue.

**Comment by toebgen** [comment]
Hi, first of all, thanks for the great tool! :-)

I was wondering, is the above mentioned feature
> 3. Once estimated, automatically update story points in Jira

already implemented?

**Comment by shridhar-tl** [comment]
Hi @toebgen - Thank you for contacting me. I had temporally deprioritized this feature as I see more work needed than initially planned and the usage of this module is slightly at the lower end. However that would definitely be part of my picks in next quarter once all the current enhancements are done.

Continue to provide your feedbacks and suggestions to improve Jira Assistant.

**Comment by markbarber** [comment]
@shridhar-tl , I really appreciate the tool.  My team is also enjoying it as our Jira installation is fairly basic in functionality.

I just wanted to add a +1 vote along with @toebgen on.  This would greatly speed up a large estimation session.
> 3. Once estimated, automatically update story points in Jira

Thank you for all you do.
