### ISSUE TITLE
Question:  Any impact to Jira Assistant with changes to Timesheet for Jira?

### ISSUE THREAD

**Issue by beamer817** [shridhar-tl/jira-assistant#232]
Atlassian has announced (10/3) a change to their free plug-in (Timesheet for Jira) that will move to a paid, monthly service effective 10/23.  I'm not sure whether Jira Assistant is built leveraging any of this tool.  Should Jira Assistant users anticipate changes to your services based upon Atlassian's change?
Thank you.

**Comment by shridhar-tl** [comment]
Hi @beamer817 - No, Jira Assistant leverages only the Core API's and not any of the API's exposed by plugins. That way, changes in plugins will not have any impact on Jira Assistant. It would continue to work the same way.

**Comment by shridhar-tl** [comment]
Hi @beamer817, I consider your query is answered and hence closing this issue. If there is something more to discuss, please feel free to reopen this issue or start a new thread in discussion forum.
