### ISSUE TITLE
Account Information Tempo for Logging Work

### ISSUE THREAD

**Issue by MaeChr** [shridhar-tl/jira-assistant#237]
In Tempo it is possible to define for each ticket for what account it should be looged the time. This is necessary if you work for several clients.
Currently it is not possible to select or define the account for logging.
Also it is possible that there is a pre defined account for a ticket so the account has not to be filled out, but on logging with jira-assistant this predefined account information is not provided in the tempo log an it is necessary to switch to tempo an fill out the account information for the logged time.

**Comment by MaeChr** [comment]
After uploading a LOG-Entry to JIRA it is actually always necessary to switch to tempo and fill out the Account.
If you log time with Tempo and the account is already defined for the issue, it no more necessary to fill out the account information.
![2022-12-01 15_32_19-Tempo - Jira Account](https://user-images.githubusercontent.com/111430216/205080156-8a4686bd-dac2-4b31-b7b0-ef3048985ecd.png)

Only if you want another Account you have to select it.

**Comment by shridhar-tl** [comment]
Hi, What is this account dropdown? Where from this is getting added? If it is getting added because of some external tools like Tempo, I'm not sure if I would be able to do anything about it. Any way, this has been the ask from multiple other users as well. Let me think about it and see what I would be able to about it.

But it would take some time. I will keep you posted.

**Comment by MaeChr** [comment]
Hello!
According to my JIRA-Admin is this from the tempo-plugin.
https://apidocs.tempo.io/#tag/Accounts

**Comment by shridhar-tl** [comment]
Hi @MaeChr, as this field is from Temp plugin, Jira API does not support pushing values for these fields. To update this value, it would require separate API call to tempo services which involves additional flow and the need for Paid version of Tempo plugin for developers and is not feasible at this point.

Jira Assistant focuses only in extending the functionality of Jira and at this point it would be difficult to support any additional plugins installed. Similar to Tempo, there were lot more such plugins available which may provide other API / fields and it would be impossible for Jira Assistant to support such plugins.

Hence I am considering this as out of scope for Jira Assistant and closing this issue. However, if any of the uses are willing to do this implementation, please feel free to raise a PR and I am happy to extend any support while development.

**Comment by MaeChr** [comment]
Thanks for the research and answer.
