### ISSUE TITLE
Import Settings never works

### ISSUE THREAD

**Issue by Yeraze** [shridhar-tl/jira-assistant#238]
**Basic Details**
- What is the version of Jira Assistant you are using? Chrome Extension 2.41
- Browser & Version? Chrome 107.0.5304.87
- What OS are you using? : [e.g. iOS, Windows] OSX

**Describe the bug**
Launch Jira Assistant, go to Settings -> 'User Groups' and Export Settings.

In another browser (In my case, Chrome on a different OSX machine) launch Jira Assistant.  Go to Settings -> 'User Groups' and Import the resulting file.

I get nothing added to my environment. Console log reports 3 entries on "Import logs":
* `Backup v1.1 created ton 07-nov-2022 12:06`
* `Settings not available in backup`
* `Groups import skipped: no integration found for <url>`

Visual inspection of the exported jab file shows all of my users and groups are properly saved in it.

**Expected behavior**
I expected my configuration of users and groups to be imported into the new browser.

**Comment by shridhar-tl** [comment]
Hi, Thank you for reporting this issue. This issue has be fixed in JA v2.44 and is already available in Web version. Soon it would be available in extension as well.

**Comment by shridhar-tl** [comment]
This implementation is done and hence closing this issue. This change is already available in Web version and you would start seeing the changes in Extension once you are updated to JA v2.44.
