### ISSUE TITLE
Add Copy WorkLog

### ISSUE THREAD

**Issue by relkcaminc** [shridhar-tl/jira-assistant#24]
As a jira-assistant user, I want to copy an existing worklog, so that a new worklog is pre-populated.

**Comment by shridhar-tl** [comment]
I am awaiting input from @relkcaminc regarding this request.

**Comment by relkcaminc** [comment]
Thank you, that works, I was looking for an option in the Ticketwise and Daywise worklog gadgets, not the calendar.

**Comment by shridhar-tl** [comment]
When you say "that works", are you happy with the existing option or you are expecting for an option in other gadgets also? Just to mention this option is also available in pending uploads gadget.

**Comment by shridhar-tl** [comment]
Hi @relkcaminc , It looks like you are happy with the option which is already available. So closing this issue.
