### ISSUE TITLE
Upload Worklog - Bad Request Error

### ISSUE THREAD

**Issue by MaeChr** [shridhar-tl/jira-assistant#241]
If you try to upload the worklog and some of the time you logged is not definied to log a work. You only get the error "Bad Request".

It would be fine if the Tickets which is/are not possible to upload would be marked with an red cross on the top right side of the log.
So it would be easy to finde the log which cause the problems to correct it. 
![2022-11-16 15_44_55-Jira Assistant](https://user-images.githubusercontent.com/111430216/202212555-caa2cb44-4d83-46c7-b47c-a44d2ed5a604.png)

**Comment by MaeChr** [comment]
![2022-11-16 15_44_55-Jira Assistant_Bad Request API](https://user-images.githubusercontent.com/111430216/203973276-95360a12-4c55-4ba4-95fc-4d09159de80b.png)

**Comment by shridhar-tl** [comment]
Hi @MaeChr - In JA v2.44, I had added icon on top right corner of each worklog to clone the worklog and to upload worklog which is not yet uploaded. You can click this icon to upload individual worklogs. This would also act as an indicator to see what is not yet uploaded. So I believe this should solve your issue to understand what is not uploaded yet.

![image](https://user-images.githubusercontent.com/37339683/209691426-3edc2c22-fa63-4a0f-ac59-6774382e7cb5.png)

Believing this would solve your issue, closing this ticket now. If you have any further suggestions or comments, please feel free to reopen this issue.
