### ISSUE TITLE
Provide a short summary of the bug here

### ISSUE THREAD

**Issue by TMGler** [shridhar-tl/jira-assistant#243]
**Before you begin**
- Ensure if you are already using latest version of Jira Assistant and Browser.
- Have you verified if this issue is already reported by others? You can search for issues with keywords.
- Did you have a look at FAQ, Features & Known issues section of https://www.jiraassistant.com to see if your question is already answered? You can also make use of search functionality in above mentioned site.
- If similar issue is already reported by others, please add more details or upvote the same issue instead of raising new issue.
- Please expect a delayed response as their is no dedicated support team and this tool is maintained by a single developer.
- Try not to club two different issue in a single ticket.

**Caution**
- Any details you provide here is public
- Please ensure you are and pasting any sensitive information like company jira url, email id, loging / credentials.
- Please ensure to mask any sensitive information from the screenshots / console logs you provide here.

**Basic Details**
- What is the version of Jira Assistant you are using?
- Browser & Version?
- What OS are you using? : [e.g. iOS, Windows] (not necessary for all issues)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (if applicable / necessary):

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Screenshots of UI issue, console error, network tab may be useful depending on the issue reported.

**Other details**
- Are their any issues in console? If yes, please attach the console screenshot.
- Is any network request failing or pending completion (network tab in Dev tools (F12) )?
- Is anyone else in your company facing similar issue?
- Since when are you facing this issue?

**Additional context**
Add any other details about the problem here.

**Comment by shridhar-tl** [comment]
Hi @TMGler , I don't see any details provided about the issue. I hope you accidentally created this issue and hence closing it.
