### ISSUE TITLE
can't change the open ticket jql

### ISSUE THREAD

**Issue by irisvdz83** [shridhar-tl/jira-assistant#246]
can't change the open ticket jql, I can click in it, select text, but I can't modify anything

**Comment by shridhar-tl** [comment]
Hi @irisvdz83, I think you would have tried changing the default query. That is not allowed. Instead, change the query for your instance as shown in following snapshot and it should work.

Please let me know if you still face any issues.

![image](https://user-images.githubusercontent.com/37339683/208459169-b5c21fd6-d5fb-419e-ac38-2aeca133c5fb.png)

**Comment by shridhar-tl** [comment]
@irisvdz83 - any updates on this? I am closing this issue assuming your issue is resolved. If you still face any issue, please feel free to reopen this ticket with more details
