### ISSUE TITLE
Typo in Poker's privacy policy text

### ISSUE THREAD

**Issue by Akimuchi** [shridhar-tl/jira-assistant#248]
When on poker start page there is privacy policy text, that contains a typo.
It's in the end "By proceeding with using the poker, you agree to all the terms and condiations."
Instead of "condiations" there should be "conditions"

**Comment by shridhar-tl** [comment]
Hi @Akimuchi, thank  you for reporting this issue. This typo error has been fixed and is published to Web version of JA. It would soon be available for Extensions as well in upcoming release.
