### ISSUE TITLE
Import Existing Worked Logged

### ISSUE THREAD

**Issue by relkcaminc** [shridhar-tl/jira-assistant#25]
As a jira-assistant user, I want my work logged directly in my open tickets to be imported into jira-assistant.

**Comment by shridhar-tl** [comment]
I am not clear with your request. But I hope your request should be something related to #1.

Please let me know if your request is something different.

**Comment by relkcaminc** [comment]
Possibly related to #1.

My use case is that I am a new user, jira-assistant imported my "open issues," however, did not import any of the existing logging on my "open issues" or any other JIRA issues I have log worked against directly in JIRA.

**Comment by shridhar-tl** [comment]
Hope this issue is resolved as part of #1 and closing it.
