### ISSUE TITLE
Request to add Summary Tab in new Worklog report

### ISSUE THREAD

**Issue by SelvalakshmiPraveen** [shridhar-tl/jira-assistant#261]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.44

### What browser are you using?

Chrome

### Feature Suggestion

This is with reference issue#260

Shridhar,

Thanks for your quick response. I see the grouping options are given already. But Summary Tab is unique and was very helpful. It gives us the insights about the total worklog of user as well as the Project in one single view in horizontal and vertical ways.

In grouping option, for example if I group by Project, I will get a worklog Project wise only. If I need to check for one user, I need to again switch the grouping. In Summary tab, As everything was in single wise, it helps us to create a report and submit it to our Management.

Grouped Option :

![image](https://user-images.githubusercontent.com/78785914/211599874-b2012815-33ab-4963-92ed-5e2b437dcda6.png)

Worklog Option (Here it more readable as it is horizontal and vertical manner) :

![image](https://user-images.githubusercontent.com/78785914/211599903-32f1399f-bc72-4981-9f44-5b1adb96a488.png)

Also, the old worklog will get removed and it will be there always?

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @SelvalakshmiPraveen - Thank you for your detailed response. I get your point. I will try to provide that option max by this month end within new report.

And to answer your second question, Yes, old worklog report would be gone, but will first hide it and only after I ensure no users are missing some functionality from it, I would completely remove it. That would take few months before it is completely removed. I would first add a message well in advance before I hide it and then would remove it later, waiting enough to address any queries I receive from users.

**Comment by SelvalakshmiPraveen** [comment]
Shridhar,

Thanks for taking up adding Summary tab as an enhancement.

**Comment by shridhar-tl** [comment]
Hi @SelvalakshmiPraveen - This implementation has been done for Date range based report with no custom grouping used. This change is now available in Web version already and in next couple for days this would be published for extension users.

But for sprint based report and when custom grouping is used, this tab would be hidden as that needs more effort and would be added later this quarter.

However, all the functionality available in old worklog report is now available in new report as well. Hence I consider this issue as resolved, but still will have this ticket open until the change is implemented for sprint report.

**Comment by SelvalakshmiPraveen** [comment]
Thanks for adding this feature back.
