### ISSUE TITLE
Upload of worklog fails - Unrecognized field "notifyUsers"

### ISSUE THREAD

**Issue by s4nf4n** [shridhar-tl/jira-assistant#262]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Not sure

### Version of Jira Assistant

2.45

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

None

### Bug Description

When I try to upload a worklog error is raised:
`Unrecognized field \"notifyUsers\" (Class com.atlassian.jira.issue.fields.rest.json.beans.WorklogJsonBean), not marked as ignorable`

After a little bit of research, Jira REST API does not support field "notifyUsers". See [Jira Docs](https://docs.atlassian.com/software/jira/docs/api/REST/9.5.0/#api/2/issue-addWorklog)
And this problem apparently seems to have been added recently:
https://github.com/shridhar-tl/jira-assistant/blob/e1bcda429580ea2b8baea5fe6365e7dc6475d386/src/services/worklog-service.js#L153

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by s4nf4n** [comment]
Yes I tried disabling the setting first, I should have mentioned it in the bug report.
But the upload sends the property anyways. The property "notifyUsers" is always present with either true or false.

**Comment by shridhar-tl** [comment]
Hi @s4nf4n - This issue is resolved in JA v2.47 and is already published. While it is already available for Firefox and Web, it is still in review by Chrome and Edge web store. For chrome I believe it should be approved by today or tomorrow and for Edge by end of this week.

As I already mentioned, for now you can use Web version by accessing https://app.jiraassistant.com to unblock you and once your extension gets updated you can continue using edge. Even Web version will connect to extension internally and so data is shared between both and you will not see any trouble switching between web and extension.

**Comment by s4nf4n** [comment]
Yes, Web version works for me, thank you.

**Comment by shridhar-tl** [comment]
Hi @s4nf4n - Extension got approved and now v2.47 is available for Chrome for you to update. If you wish to update your extension immediately, go to "chrome://extensions" enable dev mode from top right corner, and click on Update button. That would update the extensions.
