### ISSUE TITLE
Show ticket summary on calendar rather than just the ticket number

### ISSUE THREAD

**Issue by taboo180** [shridhar-tl/jira-assistant#263]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Firefox

### Feature Suggestion

When using worklog calendar or any of the calendar widgets they only show the ticket number but not the ticket title.

When viewing the calendar it would be much more beneficial to see the ticket summary/title as that typically means much more to us than just a ticket number.

![image](https://user-images.githubusercontent.com/47477508/212609318-8d3fb764-8315-4758-9ef5-723bd90e234a.png)

Thanks so much for this project!

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @taboo180 - I already have plans to implement that, but I am thinking of a way to show it as there is no sufficient space to show both summary and comments. Only if the worklog is above 3 hours, we would have space to show atleast two lines of summary which is not always the case. 

In your case you do not have any comments in your worklog and so you may feel comments can be removed and summary can be shown. But there are mix of users who use comments.

Moreover when you use comments, that comment itself give you an idea of what this ticket is about.

I will think through it and see what are the possibilities. If you have any suggestions, please feel free to let me know.

**Comment by taboo180** [comment]
Thanks so much for being so receptive to the input.

I suppose in my mind I could see two potential options given what you've described above. I think the obvious one (and probably my preference) would be to give the user the choice. I imagine that would work best by putting a toggle here:

![image](https://user-images.githubusercontent.com/47477508/213055688-991b2cfe-c233-4366-8e54-a1f5e32e9a49.png)

The phrasing is obviously up to you.

I would also then suggest having the title show up every time in the "pop up" box that you see when you hover your mouse over a calendar entry. It isn't limited by size constraints so no reason not to.

![image](https://user-images.githubusercontent.com/47477508/213056204-bae7cd88-904b-49b0-808c-ae570a9e5e18.png)

**Comment by shridhar-tl** [comment]
@taboo180 - This request has been implemented and is already published for Web version of JA. Fixes would be available for extensions in v2.48 which would be published in next couple of weeks.

Closing this ticket as it is fixed. You can test it in Web and reopen it if you still face any other issue.
