### ISSUE TITLE
Have a "today" button on the calendar to jump back to today.

### ISSUE THREAD

**Issue by taboo180** [shridhar-tl/jira-assistant#265]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Firefox

### Feature Suggestion

When using the worklog calendar it would be useful to have a "today" button to jump back to the view that includes today's date. This will be useful when scrolling a few weeks/months into the future/past to be able to get to today's current view with a single click.

![image](https://user-images.githubusercontent.com/47477508/212611107-fa81cba9-e75d-461b-9543-74619af87c08.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by taboo180** [comment]
Thanks shridhar, I'm of the opinion that if the function of the buttons is clear then it shouldn't be a concern. However I won't tell you how to suck eggs =)

**Comment by shridhar-tl** [comment]
@taboo180 - This request has been implemented and is already published for Web version of JA. Fixes would be available for extensions in v2.48 which would be published in next couple of weeks.

Closing this ticket as it is fixed. You can test it in Web and reopen it if you still face any other issue.
