### ISSUE TITLE
Calendar days show in a "MM/DD" format despite a "DD-MMM-YYYY" format being chosen in general settings.

### ISSUE THREAD

**Issue by taboo180** [shridhar-tl/jira-assistant#266]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Hi,

There are a number of "DD/MM" and "MM/DD" date formats as options in "general settings". Despite choosing a "DD/MM" option the Calendar still shows "MM/DD":

![image](https://user-images.githubusercontent.com/47477508/212611975-fa4bc334-6551-4c01-a174-5ccdac8a46b4.png)

However calendar still shows "MM/DD" format:

![image](https://user-images.githubusercontent.com/47477508/212612050-66a75691-ab95-4cbe-afd6-26e93449f516.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @taboo180 - Thank you for contacting me. This has been a known issue over years and already multiple users has reported about similar issues with calendar in #55 and #146. However there are some limitations with the calendar control I'm using and I do not see any straight forward option to support this date format.

I will have this ticket open and see if there are any updates in the calendar component supporting this configuration.

**Comment by shridhar-tl** [comment]
Hi @taboo180 - This issue has been resolved and is already available in Web version. It would be available in extension from v2.48 which would be published in another couple of weeks.

Closing this issue considering this issue is resolved. You can look at the changes in Web version for now and feel free to reopen this ticket if you observe something is not as expected.
