### ISSUE TITLE
Name of tabs in Dashboard

### ISSUE THREAD

**Issue by MaeChr** [shridhar-tl/jira-assistant#270]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Not sure

### Version of Jira Assistant

v2.47

### What browser are you using?

Firefox

### Feature Suggestion

It is possible to add individual Reports to a site and group them by tabs. But in the tabs i didn't find the possibility to change the name of the tab.
It would be nice if it is possible to change the name of the tabs or display the name of the report in the way it is if the reports are not grouped.
![Reports](https://user-images.githubusercontent.com/111430216/213102802-b8d1ab90-9a69-4ce3-8b11-97022d4add01.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @MaeChr - This issue has been partially resolved. Now if you remove the gadget and add it again to dashboard, then it would start showing the name. However if you change the saved report name at later point it won't automatically update in the gadget, it would continue to have the old name and you will have to remove it and add it again for the new name to reflect. This is the max I can do at this point based on how things are working currently.

This would be available for extension users in next couple of weeks as part of v2.48 build and you should see it in Web version by tomorrow just in case if you would like to have a look at it before it is published to extension.

 I hope this should solve your issue and hence closing this ticket. Please feel free to reopen this ticket if you see something is not working as expected.
