### ISSUE TITLE
Unable to login on firefox

### ISSUE THREAD

**Issue by filippo-bodini** [shridhar-tl/jira-assistant#275]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Not sure

### Version of Jira Assistant

2.47

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

the Jira assistance extension fails to integrate with the company where i work, (https://jira.siav.it/) showing this error:

Unknown server
This is not a valid Jira server url or the server does not respond.

It seems to be a problem with my site but on chrome works perfectly. This plugin was used on firefox until a week ago, then stopped to work. I reinstalled the latest version but nothing happened. Api doesn't seem to start any call because i don't see anything on network / xhr
![screenshot error](https://user-images.githubusercontent.com/39699912/216564670-848ce331-e641-48a8-bb62-c24b47a21eb7.jpg)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @filippo-bodini, How id you verify network log? In Firefox, there is no straight forward way to inspect the popup over window of extension.
Try accessing the following integrate page directly in Firefox browser and there you would be able to check the network log. See if there are any console errors as well. Just in case if it integrate properly, then you would be able to use the extension there after.

moz-extension://55178e35-1987-4feb-a251-d8df8a84087e/index.html#/integrate

**Comment by filippo-bodini** [comment]
sorry @shridhar-tl , if i enter in the bar, if I enter
moz-extension://55178e35-1987-4feb-a251-d8df8a84087e/index.html#/integrate
nothing happens and if I try to click on options near the extension title

![image](https://user-images.githubusercontent.com/39699912/217518528-ca6adba4-c58e-4172-83a9-07730ff6cbef.png)

the menù loads for a moment and disappears very quickly. seems that the whole application is flawed. The version is the latest con win 10. I'll try to reinstall firefox from scratch

**Comment by shridhar-tl** [comment]
Hi @filippo-bodini , When you try to load the link you should see the page like in following snapshot. From that page you should be able to integrate or press F12 and see the console errors. When you say nothing happens, I'm not clear what you mean. Can you try it again and if that did not work, can you please send me a screenshot of console log.

![image](https://user-images.githubusercontent.com/37339683/218293154-d1e07239-5294-41d0-a498-2a7d401d8f17.png)

**Comment by filippo-bodini** [comment]
hi @shridhar-tl , sorry for the inconvenience. Plugin restarted working after I cleaned all the cache. If the organization page is blocked for legacy or wrong certificates, the plugin crushes without noticing the error. Now, after the cache clear it seems to work as expected, you can close the bug.
