### ISSUE TITLE
SPRINT REPORT - Can not see "Team Managed Software" Projects but only Company Managed

### ISSUE THREAD

**Issue by SingletonM** [shridhar-tl/jira-assistant#277]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Desktop App

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.47

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

I have stopped being able to see "Team Managed Software" projects in the Sprint Drop Down, i can see them as projects, but not allowed to put them into Rapid View. The only projects i can now see in the Sprint reports are "Company Managed Projects" with boards. 

I used to have this functionality until an update over Dec 2022. Can you please tell me if there is a way through Sprint report i can see the boards / sprints for "team managed software" i only have 10 or more  projects

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
@SingletonM - I was not aware of this issue so far and right away do not have a solution handy. I will have a look at it and try to provide a fix by end of this week or ASAP.

**Comment by shridhar-tl** [comment]
Hi @SingletonM - This issue has been resolved and is already published for Web Version of tool. It would be available for extension users as part of JA v2.48 release which would happen by end of this month.

For now, you can access web version and generate report. Additionally you can try to add your board in general settings default values tab -> Rapid view. Once you add it from Web Version, I hope in extension it would persist the value and you should be able to generate report. If not, you can continue to use Web version until updates are pushed for extension.

**Comment by SingletonM** [comment]
I can confirm that the WEB version is now working as expected, thank you so much for your help & speedy response.
