### ISSUE TITLE
New gadget: Sprint burndown chart

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#28]
Need a gadget which will display the sprint burn down using line chart.

This gadget would be implemented only based on popularity. If you would like this gadget to be implemented then +1 this ticket.

**Comment by dobrescu** [comment]
+1

**Comment by roverdev** [comment]
+1

**Comment by shridhar-tl** [comment]
This feature can be easily achieved using Report Builder module and hence closing this issue.
