### ISSUE TITLE
Hide in calendars non working days option

### ISSUE THREAD

**Issue by xathick** [shridhar-tl/jira-assistant#284]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.48

### What browser are you using?

Chrome

### Feature Suggestion

Add the option to hide the non-working days in calendars, hidding the columns it displays.
![image](https://user-images.githubusercontent.com/14039042/221580003-51b183d2-dd6d-44c3-bfc1-eccd6a8cb48e.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
@xathick - This implementation has been done and would be available for extension users as part of JA v2.49.

Hence closing this ticket considering this issue is resolved.
