### ISSUE TITLE
Add Assignee to Worklog - [Pending Upload]

### ISSUE THREAD

**Issue by AFSkier** [shridhar-tl/jira-assistant#286]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.47

### What browser are you using?

Chrome

### Feature Suggestion

Please add "Assignee" to the "Worklog - [Pending Upload]" gadget. Preferably after the Summary column, like the "My Bookmarks" gadget. This would be very helpful for quick validation to see if the task I'm uploading is assigned me or someone else. It is easy to transpose the Ticket No. and accidently log time on task that happens to be assigned to someone else.
![Add Assignee to Worklog -  Pending Upload](https://user-images.githubusercontent.com/30637887/222859649-1b747c0b-706d-4f28-9d08-1161ef2bad58.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @AFSkier - Assignee column is added to pending worklog gadget and would be available in JA v2.49.

Hence closing this ticket considering this issue is resolved.
