### ISSUE TITLE
Change columns visibility in new version of Worklog Report

### ISSUE THREAD

**Issue by bagau** [shridhar-tl/jira-assistant#287]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.48

### What browser are you using?

Other chromium based

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Linux

### Bug Description

Hi. New version of Worklog Report doesn't save visible columns. But old version is deprecated and I should set visible columns every day.

I used the old version before it has deprecated and there were correct working of setting visible columns.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Thank you @bagau for reporting this issue. I will look into it and fix it ASAP. Until then you may proceed with using Old Worklog report if required. Though it is deprecated, it would stay as long as all the users are comfortable with using the new report and all the reported bugs are resolved.

**Comment by shridhar-tl** [comment]
@bagau - This issue has been resolved and would be available as part of JA v2.49. It would take few days before I can publish this change for extension users, however, it would be available in Web version within next couple of days.

Hence closing this ticket considering this issue is resolved. You can verify this fix in Web version next week and in case of any further issues please feel free to reopen this ticket.
