### ISSUE TITLE
Advanced Filter (JQL) Empty

### ISSUE THREAD

**Issue by chougrani** [shridhar-tl/jira-assistant#29]
Hi, 
On custom report, no JQL is generated when I add filter.
There JS error. 
On google Chrome :  Version 66.0.3359.139 (Build officiel) (64 bits)
![capture](https://user-images.githubusercontent.com/5504735/40062369-5aa7ff06-585b-11e8-899d-5d0af57be7b6.JPG)

**Comment by shridhar-tl** [comment]
Hi @chougrani , Thank you for reporting the issue. I will look into this issue and will fix it with in this week end. But if you could share the screenshot of the filters page also, that may be helpful in identifying the issue. But if those filters contains something official and cannot be shared then no issues. I will try to sort out the issue.

**Comment by chougrani** [comment]
Ok, It seems it works again.

Kinds regards

**Comment by shridhar-tl** [comment]
This issue should be something related to the value you provide. If you notice this issue again let me know if you could guess based on what type of field or value it caused this issue.

**Comment by shridhar-tl** [comment]
This issue seems to be resolved and hence closing the issue. If anyone again face it you can reopen this ticket.
