### ISSUE TITLE
Wrong Month displayed in Worklog Calendar and wrong color in worklog report (dark version)

### ISSUE THREAD

**Issue by SSeltonrijch** [shridhar-tl/jira-assistant#296]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

2.48

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

In the extension version I see the months with \Jan behind it:
![image](https://github.com/shridhar-tl/jira-assistant/assets/124683961/72283ccc-fd39-4747-b7f4-6844a184dca0)
While in the web version, I don't see this problem:
![image](https://github.com/shridhar-tl/jira-assistant/assets/124683961/f9ae28d7-ca5b-41ab-adcd-d2fee7a314b6)

Also the display of Worklog Report in the JA extension version and web version is not readable when containing multiple user groups:
![image](https://github.com/shridhar-tl/jira-assistant/assets/124683961/7d344a1b-7c79-43c2-95f6-b8a13ca04363)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Thank you @SSeltonrijch for reporting this issue. The first issue you reported about Month name wrongly displayed is already resolved and as you mentioned is available in Web version. Next time the extension is published, this issue would be resolved.

Second issue about dark theme in worklog report is resolved and is now available for Web version. Soon after extension is publish, this would be resolved for extensions as well in JA v2.49.

Closing this ticket considering both the issues reported are resolved. Please feel free to reopen it if you still face any other issues.
