### ISSUE TITLE
"My open tickets" gadget shows closed JIRA issues

### ISSUE THREAD

**Issue by relkcaminc** [shridhar-tl/jira-assistant#30]
The "My open tickets" gadget is showing closed tickets.

![myopentickets_closedissues](https://user-images.githubusercontent.com/38988091/40446589-ede9a238-5e8c-11e8-9181-4d3b88a78f17.PNG)

**Comment by shridhar-tl** [comment]
Hi @relkcaminc, This issue has been resolved and will be available from v0.51 onwards. It is not yet published and will be available within this week end.

**Comment by relkcaminc** [comment]
Thanks so much, glad to have this resolved.

**Comment by shridhar-tl** [comment]
Assuming this issue is resolved and closing this ticket. If you encounter any issue with this, you can reopen this ticket.
