### ISSUE TITLE
Timers don't show on Board without Rank enabled

### ISSUE THREAD

**Issue by talltechdude** [shridhar-tl/jira-assistant#300]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

2.48

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

MAC OS

### Bug Description

Worklog timer play/pause/stop buttons don't appear for Jira Boards that don't have rank enabled. Without rank enabled, the CSS class `.ui-sortable` is not added so the selectors don't work: https://github.com/shridhar-tl/jira-assistant/blob/d904205af0167c32e9337cac8dcc7d8dc98e9c9a/src/content-scripts/jira-board.js#L8-L12

Can we remove this class from both these selectors? Retaining `div.js-issue` seems to still target the correct elements from my testing, and allows the use of non-ranked boards (e.g. board sorted by priority etc)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @talltechdude, Thank you for reporting this issue. This issue has been fixed as per your suggestion and would be available as part of JA v2.49 for extension users.

Closing this ticket hoping this issue is resolved.
