### ISSUE TITLE
Problem with retrieving data from custom fields in time report

### ISSUE THREAD

**Issue by TueDissingWork** [shridhar-tl/jira-assistant#305]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

2.49; Build: 23-May-2023 04:13:52 AM

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

I want to add additional fields to the worklog report, in order to make it easy to see where the time is spend. But somehow I am not able to add any additional fields.
First I tried with some of our custom fields, which didn't work. Also just tried with the standard "Status" field.

No errors, but also no data, where I expect it to.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by TueDissingWork** [comment]
Well it actually looks like the requested custom fields isn't part of the request to Jira, which would explain why that are not returned

**Comment by TueDissingWork** [comment]
> Hi @TueDissingWork - When you mean "no data", are the columns getting displayed in report or not?
>  
> Please provide more details on what is happening with your end.

Just to further clarify; the columns are shown but seems to contain no values for the individual fields. And as stated above, it seems that these fields isn't part of the request/search query.

**Comment by shridhar-tl** [comment]
@TueDissingWork - I tried enough with cloud version of Jira and I was not able to reproduce it. I do not have data center version of Jira at this point. I will try to setup an instance this weekend and will try to reproduce it. Will get back on this by this week end.

**Comment by shridhar-tl** [comment]
@TueDissingWork - I have done Data center version of Jira setup and was able to reproduce the issue. This was due to the difference in API schema between Cloud and Datacenter version of Jira. I have resolved the issue and the fix is already published to Web version of Jira.

Please verify the fix by try to use web version and let me know. I will push it to extension users soon after that.

**Comment by TueDissingWork** [comment]
> @TueDissingWork - I have done Data center version of Jira setup and was able to reproduce the issue. This was due to the difference in API schema between Cloud and Datacenter version of Jira. I have resolved the issue and the fix is already published to Web version of Jira.
> 
> Please verify the fix by trying to use web version and let me know. You will have to unselect and reselect the columns once again from settings page as old configuration would be wrong. I will push it to extension users soon after that.
> 
> Note: Web version with work with extension for data. It does not store or retrieve any of your credentials. It just uses latest code to display your data provided by extension. So you need not worry about reintegrating with Web version. In fact once you unselect and reselect appropriate columns, even extension will start populating the data as the configuration would get corrected in extension.

Very nice.
Just verified it in the web-based version. Fields are populated as epxcted.

Thank you for the really quick fix!
