### ISSUE TITLE
Worklog Report does not work with actual jira cloud

### ISSUE THREAD

**Issue by buryndin** [shridhar-tl/jira-assistant#307]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

2.49

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Worklog Report shows an empty report.
But response from server contains worklog records
There are no issues in chrome console

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
@buryndin , Does the response from server contain the users added by you and contains worklog for given date?

I understand you say report is empty, but still that screenshot may help me understand something more. Please send me a screenshot of that empty report.

Also there are couple of filters and configuration in report which could have caused this behavior. Particularly look at Log filters tab and see if "Show all worklogs" option is selected.

Also let me know if you are generating report based on Sprint or date range.

**Comment by buryndin** [comment]
If I selected 'Show all worklogs' I get worklog for all users. But I only need report for given users.
If I try to get report for particular users I only see report for me:
![image](https://github.com/shridhar-tl/jira-assistant/assets/10330000/3ef80681-7e0b-4b38-99d3-6670d2d571bf)
but response from server also contains worklogs for other users:
![image](https://github.com/shridhar-tl/jira-assistant/assets/10330000/57593c87-579c-46e6-b731-cc7bc30acad1)

**Comment by shridhar-tl** [comment]
@buryndin , If you are an existing user and you have been using the report from some time, then try to remove and add couple of users from user groups and see if report is pulled appropriately.

In case of user migrations, this issue use to happen sometimes. Removing and adding the user again in user groups may solve it.

First try to remove and add only couple of users. Only if it works, you can do that for remaining users and issue would get resolved. Please let me know once you tried it.

**Comment by buryndin** [comment]
Yes, it is working now. Thank you!

**Comment by ecarray** [comment]
Hello, it does not work for me :-( I add the same comment in the ticket Report log - Hours reported are missing #402
