### ISSUE TITLE
Nothing is visible on UI

### ISSUE THREAD

**Issue by koraybilgin** [shridhar-tl/jira-assistant#312]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

latest

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

For the last two days, niether Chrome plugin nor web link is not working. Nothing is visible on the page, no error is listed as well.
![Untitled](https://github.com/shridhar-tl/jira-assistant/assets/141008417/9f93fb8c-da80-45b9-80b8-4280618adc5f)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @koraybilgin - Thank you for reporting this issue. This issue is already resolved and JA is up and working now.

Closing this issue now considering reported issue is resolved. Please feel free to reopen it if you see any other issues.
