### ISSUE TITLE
Worklog calendar

### ISSUE THREAD

**Issue by carlosherranz** [shridhar-tl/jira-assistant#316]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.52

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

When you check  "Hide weekends from calendar view" in Calendar configurations and you exit that view and then you come back, only the blank screen appears.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @carlosherranz - This issue has already been resolved in v2.44 and is available for Chrome, Firefox, Web and Cloud app users. However, publish is still being reviewed in Edge web store. I expect it to be published for Edge in next couple of days which should resolve the issue.

But as a temporary workaround, you can go to General Settings and once change the working days configuration (i.e. unselect and reselect any of the day selected) which would resolve this issue.

Hope that helps.
