### ISSUE TITLE
New Feature: Ability to filter Logged Work report against a JQL (list of issues) over a time period

### ISSUE THREAD

**Issue by Alinoe22** [shridhar-tl/jira-assistant#32]
As a Product Owner
I want to report on the logged time against a subset of JIRA issues for a given time period
So that I can compare estimates against actuals

------

Currently the "Worklog[User Daywise]" view is great to see time entered by the team on any item during a period. But it is not possible to filter this view for a subset of JIRA issues, and the view cannot be grouped by epic and constituent stories / subtasks, making it difficult to see how much time in the period was spent on a set of issues.

Equally you can create a Custom Report on specific issues with a JQL and add Log Work as a Display field. But then the report shows **any** log entry for these issues, and it is not possible to filter them by time period.

Either of these 2 options would meet my needs.

**Comment by shridhar-tl** [comment]
This requirement will be fulfilled as part of #41 using which user can build a new report like User Daywise with all the required fields & functionalities.

**Comment by shridhar-tl** [comment]
Part of this requirement is fulfilled as part of issue #4 .
