### ISSUE TITLE
UI Improvement For Msg Count

### ISSUE THREAD

**Issue by chenzeshenga** [shridhar-tl/jira-assistant#323]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.54

### What browser are you using?

Edge

### Feature Suggestion

![image](https://github.com/shridhar-tl/jira-assistant/assets/19517175/59f61162-8223-4f29-a1b8-7698c24032d1)

maybe use `99+` as msg count which is greater than 99.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @chenzeshenga, Thank you for highlighting this issue. This issue has been resolved and is already available in Web version.

It would take some time for extension users to get the updates. It would be available as part of JA v2.56 which is expected to be released next month.

To start experiencing quick bug fixes, switch to Web which is as secured as extension with sooner bug fixes.
Learn more about web version by visiting [JA Website](https://www.jiraassistant.com/why-web-version/)

Closing this ticket as the issue has been resolved. Please feel free to get back to me for any other queries.

**Comment by chenzeshenga** [comment]
verified in extension v2.56, looks good
![image](https://github.com/shridhar-tl/jira-assistant/assets/19517175/1d604bec-1d7d-4b38-8615-3f37cca65138)
