### ISSUE TITLE
Can't save Custom report

### ISSUE THREAD

**Issue by dporopat** [shridhar-tl/jira-assistant#326]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.55

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Linux

### Bug Description

I'm trying to create a Custom Report but I'm unable to click on any button (Save, View Report).

Also, when I move from JQL tab to the Display Settings tab, and then return back, my JQL is deleted.

I have tried this in the both extension and web versions. I also tried it in Firefox, but I have the same issue. 

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by dporopat** [comment]
![image](https://github.com/shridhar-tl/jira-assistant/assets/144994019/a2cfeb77-2318-446c-ad58-7e7c106ed9f2)
I only see this as potential problem.

**Comment by shridhar-tl** [comment]
Hi @dporopat, Thank you for reporting this issue. This issue has been resolved. I will soon deploy it to web version. Once deployed, temporarily you can use Web version to create the report and continue to use it with extension.

**Comment by shridhar-tl** [comment]
The change is already available in web version and would take up to a weeks time for it to be published to extension users.

Closing this ticket considering this issue is resolved. Please feel free to reopen it if there are additional conserns.
