### ISSUE TITLE
Jira Assistant doesn't work correctly after Jira Cloud migration

### ISSUE THREAD

**Issue by VeruBeru13** [shridhar-tl/jira-assistant#330]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.56

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Hello everyone,

we're using Jira Assistant as a reporting and controlling tool almost 6 years. 

On friday 22 we migrated our Jira to Cloud, I set a new URL in Jira Assistant so I´m connected, but If I log work on any issue in Jira it does not appear in Jira Assistant. It show in Tempo we have as a plugin, but I don´t use Tempo for work (for many reasons).

I'm desperate cos I don't know what and where to set correctly.

For example: 

1) I log work on Jira Cloud issue - it appears on issue, in Tempo but does´n t appear in JA. 

2) I log work in Tempo - it appears on issue, in Tempo, but it doesn´t appear in JA

3) I log work in JA - it appears in issue and even in Tempo
![image](https://github.com/shridhar-tl/jira-assistant/assets/146190188/e2f8f025-9747-4c29-a65d-dbb91951e92a)

We also have and old Jira URL connected with JA and every point above work fine.

Does anyone have the same problem?

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @VeruBeru13 , Thank you for contacting me.

Jira Assistant works better with Jira Cloud than data center version and so you need not worry about the compatibility.

I could think of one possibility as of now. After migration, if indexing has not yet been proper, then such issues can happen for a while with Jira. This is not a long term issue usually. It should automatically get resolved after next automatic indexing which happens within Jira.

If you feel this is persisting for a while now, then first thing you can do is check with your Jira Admin to see if Jira is properly indexed.

Or you can check network tab of Jira Assistant and see if Jira is returning that specific worklog in API call while generating report. If it doesn't return then you can be sure its indexing issue only and go back to your Jira Admin with scenario.

Also ensure it not some kind of human error. Say like time zone difference and its shown in some other date. Your Jira profile and your local system time zone should match with your local time zone.

**Comment by shridhar-tl** [comment]
Hi @VeruBeru13, Are you still facing any issue? It has been more than 3 weeks and haven't heard back from you. So I hope the issue is resolved and hence I am closing this ticket.

Please feel free to re-open this ticket if you are still facing any issues.
