### ISSUE TITLE
Grouping not working for Custom Report on UI Beta

### ISSUE THREAD

**Issue by Alinoe22** [shridhar-tl/jira-assistant#34]
* Go to the new UI Beta view
* Create a Custom report with a few displayed fields
* Group by the first entry (mine is a string) and click on View Report
* This never displays the result (a rotating arrow is displayed)

Do the same with the old UI and the report display quickly

**Comment by shridhar-tl** [comment]
I will look into this issue and fix it ASAP.

**Comment by shridhar-tl** [comment]
Hi @Alinoe22, I had identified this issue and provided a fix for it and is available from version v0.50. I believe you shouldn't face this issue again. If you face it again then please let me know with the console error.

This fix is currently only available in chrome version. If you are using Firefox version then it will be available within this weekend.

**Comment by shridhar-tl** [comment]
Hi @Alinoe22, Assuming this issue is resolved, I am closing this ticket. You can reopen it if you are still facing it.
