### ISSUE TITLE
Cloud App version installation loop.

### ISSUE THREAD

**Issue by carl-klitscher** [shridhar-tl/jira-assistant#341]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Jira cloud App

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Latest

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

I have admin rights to a cloud version of Jira and had installed the Jira Assistant a couple of weeks ago to test functionality. It worked very well so attempted to get the MS Outlook feature operational which failed as I don't have MS admin rights. 

After a few days I found a colleague who had the correct MS Admin rights so worked with them to get the permissions set up but... they were getting a different error (couldn't find a resource) during that process. I then tried on my id and ended up getting the same error and not actually getting to the MS Authentication page.

I noted that there had been an update to the code so deleted the Jira Cloud App and then tried to reinstall it but have ended up in a loop situation where I keep being bounced between the Jira Marketplace page and the installation page without ever getting the app reinstalled.

I'm not seeing any obvious errors in the browser logs indicating there are issues but then I'm not entirely sure what an error might look like.

Additional information - I also asked my colleague to try the browser extension (which I also have installed) but they couldn't as it was being blocked by the corp firewall... got that resolved and the extension can now be installed. They then got the correct MS authentication panel and have approved that and I can now access my outlook calendar through the extension on Chrome... works beautifully.

I've asked the infrastructure people if there is also a firewall or other block on the Jira Marketplace but they've not seen any traffic problems. Could still be a firewall issue so would a constant installation loop be an expected outcome of that or is it something else?  

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @carl-klitscher - I will look into the code and get back to you by this week end.

**Comment by carl-klitscher** [comment]
Hi @shridhar-tl thanks. The only other thing I can offer is an when I click on the 'Install Jira cloud app' hotspot in the relevant marketplace (https://developer.atlassian.com/console/install/3864d3bc-aad3-4650-ac35-e15af61fd92d?signature=50284775421a3ea30543ccd56a6b1bf125c3784aab7398c35b85d9e9719e4cd1&product=jira) I get an entry from the console log as follows:

Request URL: https://developer.atlassian.com/gateway/api/session/heartbeat
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 104.192.143.15:443
Referrer Policy: strict-origin-when-cross-origin

Let me know if there is anything else I need to check for you.

**Comment by shridhar-tl** [comment]
Hi @carl-klitscher - I had validated this last week itself and I was not able to reproduce the issue you mentioned. However I was able to reproduce different issues with Outlook integration. This is not an issue with JA and it appears to be issue with Jira itself. Redeploying the latest code also did not solve the issue. So I had raised a support ticket with Atlas.

From my previous experience, Atlas support team is helpful and is quick at resolving issues (better than me at least).

Hope they will resolve this issue as well soon. I will get back to you once I have some updates on this.

https://community.developer.atlassian.com/t/oauth-for-3rd-party-application-like-outlook-not-working/74463

**Comment by shridhar-tl** [comment]
Still Atlassian did not respond to my support ticket. So I am still waiting on this.

**Comment by OzanGurleyen** [comment]
@shridhar-tl I don't understand exactly if my issue is exactly the same issue as listed here but I recorded my issue, as an admin of my Jira instance, I am not able to install this. I hope the video helps.

https://github.com/shridhar-tl/jira-assistant/assets/93138541/228928c5-5021-456d-9da8-fa2de36f379d

**Comment by shridhar-tl** [comment]
Hi @OzanGurleyen - The issue you are facing is not related. Once again this is also issue with Atlassian site. They for some reason considering private version also and pointing to wrong Url from installation link. But when it reaches it properly picks public version only and does not show installation option.

This message may not make any sense to you. But the root cause for the issue is identified and working on solving the issue. It is not just for you. But unfortunately no one was able to install the tool since few days which I realized just couple of days back. I have just done what ever is required from my end by publishing the private version which was in draft state so for. It's now with Atlassian support team to review and approve it. Hope it should resolve the soon.

**Comment by shridhar-tl** [comment]
Hi @OzanGurleyen - The review of latest version is done and is approved by Atlassian. Hence I believe you should be able to install it now. Please have a look at it and see if you were able to install it and get back to me if you still face any issue.

**Comment by carl-klitscher** [comment]
Hi @shridhar-tl , had another go at installing this yesterday and as if by magic, it worked... No issues... clean install from start to finish... 

No idea what has changed however I have noticed in the past that Atlassian can take weeks to 'clean up' stuff that gets deleted... old UID's, domains etc. So maybe they just hadn't gotten round to it... or maybe it was your update... certainly nothing I can identify or pinpoint to help anyone else :-(

Anyway, thanks for your help with this. Much appreciated.

**Comment by carl-klitscher** [comment]
As per previous note... Installation now works for no obvious reason.
