### ISSUE TITLE
Jira assistant for Firefox not existing

### ISSUE THREAD

**Issue by kkrajcek** [shridhar-tl/jira-assistant#36]
From Jira Assistant description I saw that it should be also supported within Firefox

For Firefox: https://addons.mozilla.org/en-US/firefox/addon/jira-assistant/

Link does not work and plugin can't be fount for Firefox

**Comment by shridhar-tl** [comment]
Hi, Due to some compatibility issue with latest version of firefox it got disabled. I will re enable it this week end. You should see it available again in the same url.

**Comment by kkrajcek** [comment]
Thank you

**Comment by kkrajcek** [comment]
Hi, I still do not see this addon

**Comment by shridhar-tl** [comment]
Sorry about it. I got held up last week with some official work. So unable to work on this. Will definitively be enabled by this week.

**Comment by shridhar-tl** [comment]
This issue is resolved. Now it is available in Firefox add-on store.

**Comment by kkrajcek** [comment]
Now it is there. Thanks. Closing Issue.
