### ISSUE TITLE
Unable to integrate with Outlook Calendar

### ISSUE THREAD

**Issue by rikiyanuar** [shridhar-tl/jira-assistant#361]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud version of Jira

### Version of Jira Assistant

I'm using Web version

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

MAC OS

### Bug Description

I had already integrated with my Oulook Calendar. Suddenly last week an error appeared. I tried to re-integrate on the settings page and the error "Unable to integrate with Outlook Calendar!" appeared.
I looked in the console log and there was only the error message "Outlook integration failed with error: "
Is there any solution to this?

<img width="427" alt="Screenshot 2024-08-12 at 10 27 49" src="https://github.com/user-attachments/assets/cf40cb19-a94e-4944-b8a3-0f0bcda6e068">

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by fruehaufm** [comment]
Same here... I think it started on 08.08.2024. Before that it worked like a charm. I tried it with Edge and Chrome with the extension (v 2.58) and web version on Windows.

**Comment by WaldvogelMGB** [comment]
Same on Firefox (MacOS). The entire team noticed it this morning, so might still have worked on Friday.

**Comment by rikiyanuar** [comment]
> Same on Firefox (MacOS). The entire team noticed it this morning, so might still have worked on Friday.

Indeed. It still worked on Friday.

**Comment by WaldvogelMGB** [comment]
From the error message, it seems that the Azure Application key that Jira Assistant uses has expired. It would need to be renewed and a new update pushed.

Maybe individual users could also register their own key with Azure and hotwire their personal plugin to use these.

**Comment by shridhar-tl** [comment]
This issue has been resolved and you should be able to reintegrate and continue to use it.
