### ISSUE TITLE
priority sorting broken (dashboard->my open tickets)

### ISSUE THREAD

**Issue by mrs-mrl** [shridhar-tl/jira-assistant#39]
Priority sorting is broken in the dashboard gadget "My open tickets". Instead of the expected order of Highest-High-Medium-Low-Lowest the gadget sorts it as Highest-Low-Lowest-High-Medium.

We use the default priority scheme. It works in the Jira UI. Also see the attached screenshot.

![grafik](https://user-images.githubusercontent.com/22026263/42231751-aa27d5a8-7eec-11e8-82ea-18a3828010c7.png)

**Comment by shridhar-tl** [comment]
As these priority fields can be customized in individual instance of Jira, a separate API call need to be made to identify what is the sort order. Hence, as of now, it looks like a huge effort for what is achieved. Hence closing this issue as of now as won't fix. But will look at it at a later point again if feasable.
