### ISSUE TITLE
New Logo Suggestion

### ISSUE THREAD

**Issue by iraszl** [shridhar-tl/jira-assistant#44]
I suggest to use this logo for the project.

![ja](https://user-images.githubusercontent.com/11810851/43288559-3e7a3604-90f6-11e8-90e2-f6c59194ef52.png)

I can upload the source files in SVG and all other size required.

**Comment by shridhar-tl** [comment]
Thank you @iraszl . I hope their wont be any copyrights related issue for this logo / image to be used in Jira Assistant.

I will use this logo based on comments from users. I will check with few known uses and others can +1 this logo if they like it over the current one.

**Comment by iraszl** [comment]
Great. You won't have copyrights issues. I created the logo from scratch. It's very simple because it has to work as a favicon.

**Comment by shridhar-tl** [comment]
Hi @iraszl , Can you please upload SVG file for this icon. As a first step I will use this icon in Firefox version and check the response from the users. I will observe it for a week and then will apply it to Chrome extension. Once again thank you for your contribution.

**Comment by iraszl** [comment]
Sorry @shridhar-tl ! I didn't notice the request. Here is the svg.
[JA_logo.svg.zip](https://github.com/shridhar-tl/jira-assistant/files/2433710/JA_logo.svg.zip)

**Comment by iraszl** [comment]
Do you need anything else from me?

**Comment by shridhar-tl** [comment]
Hi @iraszl , thank you for uploading the icon. This icon will be used in next version of JiraAssist which is going to be published in another week.

**Comment by shridhar-tl** [comment]
Hi @iraszl , your suggestion is valid and your image is also looking good. But when I try to use it as icon or make it smaller in size, that doesn't appear well in browsers. Here is one such example. Hence I am closing this ticket as won't fix. I will try and use your color scheme and generate a new similar logo. Thank you for your contribution.

![image](https://user-images.githubusercontent.com/37339683/210483529-9abc4d10-5f87-433a-a04e-d32ee22217b7.png)
