### ISSUE TITLE
Wrong worklog aggregation

### ISSUE THREAD

**Issue by toretto460** [shridhar-tl/jira-assistant#47]
To aggregate the worklog is used the date of worklog creation, not the date of the log.

I.e if I log today for a yesterday task the app will consider that log as a today work

**Comment by shridhar-tl** [comment]
Hi @toretto460 , Can you please let me know in which part of the application it is happening so? Also please let me know which browser you are using. No where it is considered like that. One of the possible reason could be something related to the timezone difference between your local machine and the Jira Profile. Please compare that as well.

**Comment by shridhar-tl** [comment]
If this issue is still available in BETA version please reopen this ticket.
