### ISSUE TITLE
Ability to download  worklog reports as PDF

### ISSUE THREAD

**Issue by jeevanpandian** [shridhar-tl/jira-assistant#49]
It would be great if we have an ability to download the worklog reports in PDF format.

**Comment by shridhar-tl** [comment]
Export to PDF option added. Still styles are not exported exactly the same way. Will need additional effort in implementing it and will be implemented based on popularity.

**Comment by jeevanpandian** [comment]
Thanks Sridhar.

**Comment by shridhar-tl** [comment]
Closing this issue as the primary request is resolved. In case of any other enhancements, let that be as part of new ticket.
