### ISSUE TITLE
update jira url after initial setup

### ISSUE THREAD

**Issue by mrs-mrl** [shridhar-tl/jira-assistant#52]
When the jira URL changes, there's no way to simply update it. Basically things are broken and you're stuck on the dashboard. This could be easily fixed by simply re-enabling the initial setup procedure when no conenction to the dashboard was possible.

**Comment by mrs-mrl** [comment]
OK, thanks! For now we went with deleting the profile. It is not too much of a hassle, but recreating the profile is a bit tedious.

**Comment by shridhar-tl** [comment]
Hi @mrs-mrl 
This issue has been partially resolved as part of #105. You can go to Advanced Settings page and edit the url of any instance you have. But this is only possible if you are using more than once instance. If you have only one instance and if that instance is not accessible, then this solution will not help you for which I would be adding an option to change it somehow from 401 page.

**Comment by mrs-mrl** [comment]
Sounds good. Luckily we haven't had this issue again, as the URL hasn't changed since. :)

**Comment by shridhar-tl** [comment]
Jira Assistant v2.41 has options page from where you can change the Jira url and few other settings. To view options page right click on the extension icon and click options.

**Comment by mrs-mrl** [comment]
Great, thanks! I'll close this issue then.
