### ISSUE TITLE
Logged work - user daywise - pulls in work from all Jira Projects, 

### ISSUE THREAD

**Issue by zrstopa** [shridhar-tl/jira-assistant#53]
Greetings,

Love the time on task ability of this plugin!  For the canned report it pulls in hours (from groups i created) across all projects.  All my developers are the same across 5 projects yet if theres 200 hours across 5 developers I can't see which project it relates to.  It's great to see bob worked a total of 30 hours last week but in reality it was split across 5 projects and there's no ability i can see to show this. I've tried custom reports, still no help.

**Comment by shridhar-tl** [comment]
This functionality will be implemented soon.

**Comment by shridhar-tl** [comment]
Assuming this is working fine, closing this issue. If their is anything more to be done as part of this issue, this can be reopened or a new issue can be raised.
