### ISSUE TITLE
Being able to configure/disable maximum required comment length when logging work

### ISSUE THREAD

**Issue by jpammer** [shridhar-tl/jira-assistant#54]
Not sure if this was intentional, but in JIRA it is also possible to omit comments when logging work. In my opinion it should be configurable if a comment of a defined length must be added in order to be able to log work.

**Comment by shridhar-tl** [comment]
Hi @jpammer, Your request to add settings for comments length has been implemented and is available from version v0.63. Once your chrome version gets updated you should see new option under Settings -> General (menu) -> Worklog (tab). Currently the settings is defaulted to 5 chars. You can change the limit or set it to 0.

Hope this works for you. Please check and let me know if the solution works for you.

**Comment by jpammer** [comment]
Hi @shridhar-tl !
Works perfectly, thanks for adding it so quickly!
