### ISSUE TITLE
Display Time format not applied in the Calendar / Worklogs View

### ISSUE THREAD

**Issue by mrs-nml** [shridhar-tl/jira-assistant#55]
The Display Time format setting is not applied in the Calendar / Worklogs View. The Setting is set to 24 HH:MM:SS but the displayed time is 12 HH:MM am/pm.

Settings: 
![image](https://user-images.githubusercontent.com/43336384/45614488-f801cc80-ba69-11e8-8867-0a1030e6a876.png)
View: 
![image](https://user-images.githubusercontent.com/43336384/45614515-110a7d80-ba6a-11e8-9fc9-bf0214d894c9.png)

**Comment by shridhar-tl** [comment]
This issue has been partially resolved as part of #146

**Comment by shridhar-tl** [comment]
As the reported issue is resolved long back, closing this ticket. If there are any more issues, please feel free to reopen this ticket or raise new one.
