### ISSUE TITLE
Daywise/ticketwise worklog gadgets stopped working

### ISSUE THREAD

**Issue by OskarPh** [shridhar-tl/jira-assistant#56]
Daywise/ticketwise worklog gadgets stopped working.
They were working last week.

![image](https://user-images.githubusercontent.com/40005677/45674477-80957100-bb2d-11e8-97f4-2a8903c1cd38.png)

**Comment by photoghog** [comment]
This is happening to us as well.  Daywise dashboard works fine but no longer works in the gadget view.

**Comment by chadb4184** [comment]
I can confirm this is happening, as well.

**Comment by shridhar-tl** [comment]
@OskarPh - I could see their is no date range selected in your screenshot. Please check if you select a date range it is showing the data.
@photoghog , @chadb4184  - Please check if this is the case for you as well.

**Comment by OskarPh** [comment]
@shridhar-tl I did choose one of the date ranges (either by clicking directly on it or clicking on "Apply"), but I think that's the bug here, none of them "stuck".

**Comment by chadb4184** [comment]
I can also confirm the same is happening if attempting to select a custom date range, as well.

**Comment by shridhar-tl** [comment]
@OskarPh , @photoghog , @chadb4184 - This issue has been resolved and will be published by end of the day and will be available to you once your version gets updated.

**Comment by OskarPh** [comment]
It's working now. Thanks a lot!
