### ISSUE TITLE
Jira assistant errors out when account name has an apostrophe in it

### ISSUE THREAD

**Issue by photoghog** [shridhar-tl/jira-assistant#57]
We have a JIRA user who has an ' in her username.  Whenever she tries to do anything in JA, she gets the following error message.  Is there a way to fix this without have to rebuild her id?
![image](https://user-images.githubusercontent.com/43413687/46030323-71796a80-c0bb-11e8-96ab-b70265155c8a.png)

**Comment by shridhar-tl** [comment]
This issue has been updated in v0.65 of the extension. Once your extension gets updated to the latest version this issue will be resolved.

**Comment by shridhar-tl** [comment]
I did not hear back on this since long time. So I hope this issue has been resolved and hence closing this ticket. In case of any other issues please let me know.
