### ISSUE TITLE
Create report for logged time by project

### ISSUE THREAD

**Issue by iraszl** [shridhar-tl/jira-assistant#59]
A typical request from management is to have a summary of all the work done for a certain time period for a client. So the report basically would look like this:

**From Time X - To Time Y**
- Project A - 100.5h
- Project B - 50.8h
- Project C - 14h

**Comment by shridhar-tl** [comment]
Implemented as part of #53 and is available for chrome users already.

**Comment by shridhar-tl** [comment]
Assuming this is working fine, closing this issue. If their is anything more to be done as part of this issue, this can be reopened or a new issue can be raised.
