### ISSUE TITLE
Need option to view user daywise report based on sprint along with date range

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#6]
Currently user daywise report allows the user to view the worklog report based on the selected date range. New feature need to be added to the report which enables the user to select the sprint rather than selecting the date range.

**Comment by terryrankine** [comment]
Sprint would be super handy

**Comment by shridhar-tl** [comment]
This requirement will be fulfilled as part of #41 using which user can build a new report like User Daywise with all the required fields & functionality.
