### ISSUE TITLE
Worklog missing issue data when the author field is malformed

### ISSUE THREAD

**Issue by eugie512** [shridhar-tl/jira-assistant#62]
JIRA assistant is most likely not at fault here, but there are certain issue API calls that only return the `name` sub-field for both `updateAuthor` and `author`. This manifests as the issues not being pulled in to the worklog view. I'm assuming that JIRA assistant is expecting the user `key`. 

As mentioned, I'm not sure if this is a breaking change with JIRA's API, but it'd be great if we could implement some fallback for this case.

For clarification, JIRA assistant is expecting
`"updateAuthor": {"name": "user12345", "key": "user12345"}`
But what the issue call is returning in some cases:
`"updateAuthor": {"name": "user12345"}`

**Comment by shridhar-tl** [comment]
@eugie512 , Which page of the tool are you facing this issue? also if you see any console error then it would be great to attach it. But if you attach a screenshot please ensure that you don't expose any sensitive information in the screenshot.

**Comment by shridhar-tl** [comment]
Hi @eugie512 - Do you still see this issue? If so please reopen this issue or open a new ticket with all the required details.
