### ISSUE TITLE
Actual time spent not populating

### ISSUE THREAD

**Issue by Bullenj01** [shridhar-tl/jira-assistant#65]
Its probably me not you cause I'm a new user.  Whenever I try to add a worklog the Actual time spent field does not seem to be populating.  Any ideas on how to fix?

![image](https://user-images.githubusercontent.com/24844853/49816158-4ce87280-fd3b-11e8-99c7-44a755e953fb.png)

**Comment by eguardiola** [comment]
The issue must be assigned to your user in order to be displayed on the autocompletion list

**Comment by shridhar-tl** [comment]
Hi @Bullenj01 - Actual time spent will be populated only while you are editing an existing worklog. You must be using Override time spent instead. Hope you would have figured out yourself by now. If you still have any queries you can raise a new ticket. Closing it for now.
