### ISSUE TITLE
Enable to integrate my jira on chrome whereas i manage on vivaldi on the same pc

### ISSUE THREAD

**Issue by nikelkrome** [shridhar-tl/jira-assistant#66]
Before all, I want to say excellent extensions. A complete tool.
I try to install Jira Assistant on Vivaldi browser and it works well.
I try to install the same on Chrome and it failed : see the attached screenshot.
I remove all extensions, clear the cache, uninstall and reinstall chrome ... nothing changes !
Help 
![item-88676-000703](https://user-images.githubusercontent.com/5735638/49869308-598aca80-fe10-11e8-9aac-4d917360d27e.jpg)

**Comment by shridhar-tl** [comment]
Hi @nikelkrome ,
Sorry for delayed response. Are you still facing this issue?

**Comment by shridhar-tl** [comment]
I hope this issue should have resolved. If it is still not resolved, please reopen this ticket by adding console errors.
