### ISSUE TITLE
this doesn't seem to be pulling worklog times anymore

### ISSUE THREAD

**Issue by jmatzdorff-cpi** [shridhar-tl/jira-assistant#70]
I have a problem with Jira cloud since they changed logging worktime to require a description.  It's not showing up on the Jira Worklog (User - Daywise) anymore.

as the SS show below, i have certain hours that i have logged to a user (in this case, 4, 16, 6, 6, and 8 on one issue).  in the Worklog screen in Assistant, it is correctly showing the number of hours worked on the 30th, 6th, and 12th (plus some more across other stories), but the time for the 20th and 27th is NOT showing up.  no time is showing up at all.

i haven't (knowingly) changed anything.  feel free to ask me to get more data if needed, wasn't sure what all to report.

<img width="851" alt="screen shot 2019-02-28 at 2 52 13 pm" src="https://user-images.githubusercontent.com/38891812/53604176-955c4300-3b68-11e9-9681-38f8a55a34a9.png">

top line below is the user who the above time was logged against (kept names out for obvious reasons...)

<img width="1361" alt="screen shot 2019-02-28 at 2 52 54 pm" src="https://user-images.githubusercontent.com/38891812/53604185-9b522400-3b68-11e9-8cd2-7e4e497462d2.png">

**Comment by shridhar-tl** [comment]
Hi @jmatzdorff-cpi , Please check and reopen the ticket if you still face this issue in BETA version of Jira Assistant.
