### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by seanericwatson** [shridhar-tl/jira-assistant#71]
@shridhar-tl I would enjoy collaborating on this project. Would you be willing to publish the source code so I can create a branch?

**Comment by nitram509** [comment]
Same from my perspective ... having some ideas for improving project planning via Gantt Chart like view to contribute.
Is there a chance you to open the sources, @shridhar-tl ?

**Comment by nitram509** [comment]
Can be closed, I believe.

**Comment by shridhar-tl** [comment]
Closed as the source code is now available in develop branch and anyone willing to contribute can do so.
