### ISSUE TITLE
Snap to quarters of the hour when moving blocks on calendar

### ISSUE THREAD

**Issue by nineclicks** [shridhar-tl/jira-assistant#72]
Right now when moving a time log, it moves by 15 minutes. To align to a quarter of the hour, the time has to be manually entered. This also doesn't work on a closed issue even though dragging does work on a closed issue. So to be able to drag to snap to the quarter of an hour would help a lot.

**Comment by shridhar-tl** [comment]
This implementation is done and hence closing this issue. This change is already available in Web version and you would start seeing the changes in Extension and Cloud App as once you are updated to JA v2.44.
