### ISSUE TITLE
The value 'closed' does not exist for the field status

### ISSUE THREAD

**Issue by totti4ever** [shridhar-tl/jira-assistant#73]
my company has renamed some default status and now the whole extension is broken, sadly

**Comment by shridhar-tl** [comment]
Hi @totti4ever - I know it is too late. But I was inactive with development from long time and become active since couple of months. If you are still having issue using Jira Assistant, then your can just remove the "My Open Tickets" gadget from dashboard and use the custom gadget available in following link. You may need to modify the query in this custom gadget to suit your needs. Hope this helps.

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/SHARED_REPORTS.md

**Comment by igarrido-verimatrix** [comment]
The calendar / worklog view also fails due to this, I can't create new entries.

**Comment by Ismael** [comment]
The calendar / Worklog view also fails due to this. I can't create new entries. Any chance we could get a fix?

**Comment by shridhar-tl** [comment]
I am not yet sure how Calendar view is failing because of this Issue. I will figure out a fix by this weekend.

**Comment by Ismael** [comment]
When you create a new worklog on calendar, it posts to /rest/api/2/search and gets a 400: "{"errorMessages":["El valor 'Closed' no existe para el campo 'status'."],"warningMessages":[]}"
(That reads: The value 'closed' does not exist for the field 'status').

The post is doing: {"jql":"assignee=currentUser() AND resolution=Unresolved and status != Closed","fields":["issuetype","summary","reporter","priority","status","resolution","created","updated"],"maxResults":1000}

It's the same error that I get on "My open tickets", so fixing one will probably fix the other.

**Comment by shridhar-tl** [comment]
Hi @totti4ever @Ismael 
This issue has been resolved as part of #105. You can go to Advanced Settings page and edit the JQL of my open tickets to have your issue resolved. Please feel free to reopen the ticket if you face any other issue.

Hope that helps you.

**Comment by Ismael** [comment]
Very minor bug: after saving the setting I had to reload the tab for the change to take effect.

Thank you for this feature!

**Comment by shridhar-tl** [comment]
@Ismael - This was not actually a bug. This was designed the way it works. If you see the success message, it states you should reload for the changes to be reflected. This is because their would be multiple local cache at each module level and it would be hard to clear out all those.
