### ISSUE TITLE
User Day wise Timezone Issue

### ISSUE THREAD

**Issue by shaunjwaala** [shridhar-tl/jira-assistant#74]
Took me a bit to determine this one, but I was trying to "balance" worklog data from another tool (Pivot Reports) as they didn't match what is shown in this extension.  If you look at the image I provided, the horizontal totals match the cumulative total (57h 30m), however the vertical totals actually total something different (63h 30m).  The 63h 30m is what pivot reports was reporting, so I was research "why".  In that I noticed the two lines (square rectangle in image) don't show any hours, yet show a total in the vertical totals.  These both were entered at 10:19 PM PST which translates to 1:19 AM EST which is outside the range of the report (these 2 entries were made the "end date" of the report.

It would seem the worklog query and the total query are using different forms of timezone comparison.

Hope this helps you find the bug....

![2019-04-24 14_31_01-Window](https://user-images.githubusercontent.com/630152/56685489-14b94f00-66a0-11e9-9c04-eec7a5b51eb9.png)

**Comment by shridhar-tl** [comment]
Hi @shaunjwaala - Thank you for taking time to report this issue. It was bit hard to reproduce this issue as I would need relevant data. I will try it out in different ways. But if it is easy for you to check for same date range with new Beta version of extension and if the issue still exists, then I think it makes sense for me try reproducing from my end.

Never mind if it is not possible for you at this point. Will try to figure it my self. Thank you.

**Comment by Gizzie44** [comment]
I had the exact issue on my project. Total shows that there is en entry in the day worklogs, but in the day worklog there is an empty row.

**Comment by shridhar-tl** [comment]
@shaunjwaala - As this has been reported almost an year back and no updates were posted later, I assume this issue has been resolved. If you still face any other issue, please feel free to raise a new issue or reopen this issue.
