### ISSUE TITLE
Allow import cvs worklog

### ISSUE THREAD

**Issue by travnick** [shridhar-tl/jira-assistant#75]
I have big csv file with worklogs (hamster project to track time)
Unfortunately I see no way on fast importing such file into JA, and then exporting it to JIRA.

Is it possible to have such feature?

//I've tried to manually modify the JA database, but unfortunately worklogs as stored as binary data, so it's to much effort to hack the SqlLite database directly.

**Comment by shridhar-tl** [comment]
Hi @travnick ,
This was already in plan and infant already implemented it partially in old version itself but hidden as it is not fully implemented. I became quiet busy and was not able to spend time on it. But now once Beta version becomes stable, I would start implementing it one by one. At this point I do not have any timelines, but soon I will plan and keep you updated.

**Comment by shridhar-tl** [comment]
Hi @travnick - Assuming your request has been fulfilled, closing this ticket. If you have any more queries, you can either reopen this ticket if appropriate or open a new issue.
