### ISSUE TITLE
Add an option to get either ticket number or summary 

### ISSUE THREAD

**Issue by molosse14** [shridhar-tl/jira-assistant#76]
Add an option to get either ticket number or summary when listing the ticket for worklog.
Indeed, we may use General/worklog/default meeting ticket for worklog feature but instead of giving ticket reference that is not human understandable, we could have an option to list instead the summary of each ticket.

**Comment by molosse14** [comment]
This feature would be very useful :)

**Comment by shridhar-tl** [comment]
Hi @molosse14 , It looks like you refer to multiple places and hence I am not clear where exactly you are expecting summary of ticket. Would you be able to provide more details? A screenshot would make it even better for understanding.

**Comment by molosse14** [comment]
Hi @shridhar-tl, it takes place in calendar/worklogs frame - when you select the ticket to be worklogged you just have the reference list, but ref number are not meaningful - It would be great to offer a choice to get either the current behavior or displaying the beginning of ticket title, because we do not remember which ticket is referencing the subject we would like to log.
![worklog](https://user-images.githubusercontent.com/51116404/64318407-47624500-cfba-11e9-8405-da9dde3c58c6.png)

**Comment by shridhar-tl** [comment]
This would be implemented in beta version of JiraAssistant and will be available soon for chrome users and some times later for Firefox users.

**Comment by shridhar-tl** [comment]
Hi @molosse14 - Closing this issue assuming this is working fine for you. If you still have any queries, you can reopen this ticket or create a new issue.
