### ISSUE TITLE
Issue linking on custom report (widget)

### ISSUE THREAD

**Issue by Muvuk** [shridhar-tl/jira-assistant#78]
Helo,

Is there a way to add link to custom report (widget) as it works on My open tickets list?
https://prnt.sc/oaio9u

thank you

**Comment by shridhar-tl** [comment]
Thank you for raising a suggestion. But I feel sorry to say, at this point, their are no plans for any more enhancements in Custom Reports module. I am trying to provide all the options possible through Report builder module and this requirement can also be achieved using Report Builder module. I would build some sample gadgets using Report Builder module and share it through some medium and anyone can probably customize it based on their requirement. You can also build your own report and once you get familiarize with Report Builder, you can almost build any kind of report with it.

And definitely, I can support you building any reports with it. If your requirement is something useful for other users also, then you can even post it as a new requirement and I myself would build it and share it.

**Comment by shridhar-tl** [comment]
Following document should help you get started with using report builder for any custom reports.

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/SHARED_REPORTS.md

**Comment by shridhar-tl** [comment]
This implementation has been done and is now available in chrome web store. Soon will be available for other browsers as well and hence closing this issue.
