### ISSUE TITLE
Issuetype wise monthly worklog report

### ISSUE THREAD

**Issue by akumar05** [shridhar-tl/jira-assistant#83]
This is not a bug, please consider this as question/request.
I was trying to fetch worklog monthly report against "story & associated subtask" and "bug & associated subtask" from all development project I have on my Jira Cloud instance. Using worklogdate>=startOfMonth() fetch the issue where we have logged hours but export carries old timelogged also on those Jira issue. As log work date filed not appear in export not able to separate hour spent in current month.

Any suggestion.

I can fetch this on Jira server from database but on Cloud looking for solution.

**Comment by shridhar-tl** [comment]
If you are trying to fetch worklog report for just a month then it shouldn't be an issue. You should be able to use User Daywise report to fetch the worklog details. But when you talk about JQL (i.e. worklogdate>=startOfMonth()) I am little bit confussed wike from where you are trying to fetch. In user daywise report you will just have to select the date from date picker and you need not write any JQL for this case.  So need more clarity on this. A screenshot of what you try to do would explain more than you can explain through words. So if possible please attach a screenshot as well.

**Comment by shridhar-tl** [comment]
User daywise report also have option to view the report in flat table structure which can be used if you want to use it for any other purpose like some other calculation.

**Comment by akumar05** [comment]
Thanks Shridhar for reply, user daywise report has all data I'm looking for, only we need issue type and KEY (or Project) where worklogged aprt from user and logged-hours on any date.


User   Details | Aug, 2019 |   |   |   |  
-- | -- | -- | -- | -- | --
  | Thu, 01 | Fri, 02 | Sat, 03 | Sun, 04 | Mon, 05
Dipak   Shelke(time zone: Asia/Kolkata) | 6 |   |   |   | 7
Deepak   Soni(time zone: America/New_York) | 9 | 7.5 |   |   | 4.5
Rohit   Sarda( time zone: America/New_York) | 6.5 | 5 |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
Issue Type and Issue Key |   |   |   |   |  



Also do we have any option to add all users from any user group, I want to fetch daywise report for all users in jira-software-users group. I can only see add all users one by one manually.

**Comment by shridhar-tl** [comment]
@akumar05 - At this point their is no way to add all the users from Jira to fetch the report. Their would be 1000's of users and it is not feasible to generate report for 1000's of users. That can even slowdown the entire Jira server in some cases. For such usecase their should be some background processing required and this application is not meant to do such task.

But when it comes to fetching project or issue type, you can switch the report to flat structure from settings icon available in top right corner of the report which contains that information you require as well.

**Comment by akumar05** [comment]
Thanks @shridhar-tl, we can mark this request closed.

Also if there is a plan - Team can think to allow "User Group" in place of one by one user, we may restrict on MAX users in User Group.
