### ISSUE TITLE
Existing Custom Report fails to run in Beta

### ISSUE THREAD

**Issue by susan-scott** [shridhar-tl/jira-assistant#84]
**Steps to Reproduce:**
1. open an existing Custom Report which is simple:  id = "WEBRATER-579" or id = "WEBRATER-580"  or id = "WEBRATER-571" or id = "WEBRATER-627"
2. click on VIEW REPORT

**Problem**: Jira Assist says: "Action Error. One or more of the actions failed". 
This report used to run in the previous version.

**Comment by shridhar-tl** [comment]
Thank you for reporting this issue. This issue should be resolved by end of this week and you should see it working from next Monday.

**Comment by shridhar-tl** [comment]
Hi @susan-scott, Hope the issue is resolved now and hence closing this issue. If you are still facing any issue, please feel free to reopen this ticket.
