### ISSUE TITLE
Export to CSV not available in BETA

### ISSUE THREAD

**Issue by Szabotic** [shridhar-tl/jira-assistant#85]
Hi,

I am happy to see you are continuing to develop JIRA Assistant, it's a great tool.

I tried the new BETA version today and I noticed there is the option to 'download as CSV' is no longer available when using the 'Worklog Report'.

Was this intentional? Is there are plan to have this re-introduced later on?

Thanks in advance

**Comment by shridhar-tl** [comment]
This is known issue and already implemented it in most of the modules now and will be published by end of this week. You should see it working by next Monday. Thank you for taking time to report this issue and I appreciate pointing any other issue you face going forward as well.

**Comment by Szabotic** [comment]
Apologies if I have doubled up the issue, I did not spot this was already a known issue!

Thanks for picking this up and responding.

**Comment by shridhar-tl** [comment]
Not a problem. This issue is not documented anywhere so it is absolutely fine you raised it. Feel free to raise any more issues you come across.

**Comment by shridhar-tl** [comment]
Assuming this is working fine, closing this issue. If their is anything more to be done as part of this issue, this can be reopened or a new issue can be raised.
