### ISSUE TITLE
Log time field can't be edited by typing in BETA

### ISSUE THREAD

**Issue by eguardiola** [shridhar-tl/jira-assistant#86]
Hi,

Is uncomfortable the need to select the time using the UI instead of typing. I was used to change the time typing and the BETA has blocked that possibility.

Thanks for the great job.

**Comment by shridhar-tl** [comment]
Will look into it and possibly will have it editable

**Comment by shridhar-tl** [comment]
I am still facing issue publishing to Chrome web store. But latest updates (i.e. v1.3) are published to Firefox, Edge and Opera already. Hope all the issues with Firefox should have already got resolved by now.

Chrome users please be patient or use Firefox version temporarily to help with your activities. Apologies for all the inconvenience caused.

**Comment by shridhar-tl** [comment]
This fix is published now in chrome extension as well. So you should see it working going forward. Thank you all for your patience. But for getting the fix published to chrome, some permissions given to chrome extensions were removed to get the approval in review process. As a result some of the minor features were removed as well. More in particular, Report Builder feature, excel export feature, first time integration, etc., may face some issues / change in the way of implementation.

To know exactly what is impacted, see version history in the extension.

**Comment by shridhar-tl** [comment]
Closing this ticket assuming this issues has been resolved now. If any of you still face any issue please feel free to raise a new ticket
