### ISSUE TITLE
Option to add worklog on a particular ticket for a day from Worklog report

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#87]
From Worklog report, under user daywise tab, user should have an option to add worklog so that user need not switch the page just for adding it. Attached a sample screenshot.

Who ever is interested in this feature please +1 on it so that I would prioritize it accordingly.

![Worklog report](https://user-images.githubusercontent.com/37339683/64491638-85948880-d288-11e9-8cd4-76dafb6e17b7.png)

**Comment by eaberasturi** [comment]
This would be a great addition!

**Comment by eaberasturi** [comment]
This functionality is going to be great!

**Comment by shridhar-tl** [comment]
Implementation of adding worklog is done. But still the report will not get automatically updated with the newly created worklog. This will be implement later after analysing appropriate way to implement it.

**Comment by eaberasturi** [comment]
Thanks Shridhar!
