### ISSUE TITLE
Beta version - Max hours to log can't be set 

### ISSUE THREAD

**Issue by dgogoasa** [shridhar-tl/jira-assistant#88]
Using Settings->General:
Max hours to log. Very hard to set the time. However after setting it like in image 1 if you navigate away and come back it is again not set.
![Image 1](https://user-images.githubusercontent.com/13841155/64495365-59a2f280-d2dc-11e9-9a1b-3829dabf38df.png)
![Image 2](https://user-images.githubusercontent.com/13841155/64495367-6293c400-d2dc-11e9-81ef-5d5d8c027b51.png)

**Comment by shridhar-tl** [comment]
Hi @dgogoasa , You had reported couple of issues in this thread:

1) Very hard to set the time.
2) After setting the time and when you navigate back to this page settings is lost.

Out of this 2nd issue is already resolved and you can check it now. But when you say it is something hard to set, I am not clear what you mean by it. Can you once again check it now and let me know more on it?

**Comment by shridhar-tl** [comment]
@dgogoasa - Closing this issue assuming this is working fine in beta version currently. If you still face any issues, please feel free to reopen this issue.
