### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by NeoMatrixJR** [shridhar-tl/jira-assistant#89]
Darken all the things :)

**Comment by shridhar-tl** [comment]
Hi @NeoMatrixJR - Thank you for your suggestion. I am trying to use all my spare time to provide new features through which most of the users would be benefited. Based on Analytics, not even 8% of users are changing the default theme and so it looks like users are not interested in themes. So I would have this prioritized based on users request.

Anyone we would like to contribute in adding new themes can add styles and create a pull request on develop branch. More details available in following link

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/CONTRIBUTE.md
