### ISSUE TITLE
Custom Single Select Fields are not being recognized in Custom Reports

### ISSUE THREAD

**Issue by j0ech3n** [shridhar-tl/jira-assistant#90]
![JiraAssistant-CustomSingleSelectField](https://user-images.githubusercontent.com/3607596/64997216-e62d5200-d894-11e9-85dd-c5bf895ea3a3.PNG)

Custom Single Select Fields are not being recognized in custom reports. My single select field is just a list of 4 char strings (Ex. ABCD, BNMJ, etc)

Chrome APP with JIRA Server 8.3.1

**Comment by shridhar-tl** [comment]
Merging this issue with #157. Based on new enhancement, this issue would likely get resolved.
