### ISSUE TITLE
Security of Jira Assistant

### ISSUE THREAD

**Issue by iikjam** [shridhar-tl/jira-assistant#92]
Could some1 tell me more about security of this solution? Is it possible that this addon somehow will steal my data from google/jira account? Usually data stored on gmail /jira account are quite sensitive.

**Comment by shridhar-tl** [comment]
Hi,
This is a opensource project. So you need not worry about security related issues. More details available in following link.

https://github.com/shridhar-tl/jira-assistant#how-safe-is-the-data-handled-by-jiraassistant
