### ISSUE TITLE
Range select in Daywise Worklog error

### ISSUE THREAD

**Issue by LuisLorca** [shridhar-tl/jira-assistant#93]
I don't know if it's because of the update but before, in the Daywise worklog widget, when I selected "this week" it showed the days of the current week and when it finished it changed to the next one, but now I don't.

![image](https://user-images.githubusercontent.com/48026584/65862535-be4aed80-e36e-11e9-9b22-46a86f3dd4c5.png)

In the capture, last week I selected "This Week", and today is selected "Last week". Before the Beta if I selected "This week" this option will keep forever.

**Comment by shridhar-tl** [comment]
Hi @LuisLorca - This fix is available since Jira Assistant v0.68 for chrome users. Once your extension gets updated you would have this working fine. Please check it and let me know if this is resolved.

**Comment by LuisLorca** [comment]
Hi @shridhar-tl:

I have the 0.78 version. I will see next week if it still happend and I will say you anything

**Comment by shridhar-tl** [comment]
Hi @LuisLorca - Sorry, my mistake, I wrongly mentioned the version number. It is available since 0.78. So now you have the latest version then. You can verify it now and let me know.

**Comment by shridhar-tl** [comment]
I hope this is working fine now. Hence closing this issue. Please re-open it if you are still facing it.

**Comment by LuisLorca** [comment]
@shridhar-tl,

It was resolved, sorry.
