### ISSUE TITLE
"This Week"/ "Last Week" should start the week from the user setting

### ISSUE THREAD

**Issue by riteshmuhatte** [shridhar-tl/jira-assistant#94]
Based on the start of the week the **Worklog Report > Select Date Range > This Week**  should start the report from the Week begin day. This should be applicable application wide anywhere "This Week" or "Last week" is utilized.
![image](https://user-images.githubusercontent.com/18084962/66910639-890bf400-f02c-11e9-8d83-2528f3f119ba.png)

![image](https://user-images.githubusercontent.com/18084962/66910800-e43de680-f02c-11e9-9cbe-91abdac11417.png)

**Comment by shridhar-tl** [comment]
Hi @riteshmuhatte, This issue has been resolved long back and hence closing this ticket. Please feel free to reopen it if you feel this is still an issue.
