### ISSUE TITLE
[Request] Display total worked log without clicking

### ISSUE THREAD

**Issue by taimaiduc** [shridhar-tl/jira-assistant#96]
As a user, I want to see total logged time on the month view mode.
We can see an overview. What day we are missing or not enough 8 hours/day
![image](https://i.imgur.com/ZsT2XMs.png)

**Comment by shridhar-tl** [comment]
Hi @taimaiduc, The height of your screen has to be at least 490px to show even 1 entry. If your size is lesser than that, there is no feasibility at this point to provide a solution. Hence closing this issue as not fixable
