### ISSUE TITLE
Update Calendar/Worklogs Week View to use row banding

### ISSUE THREAD

**Issue by EH-DUMAC** [shridhar-tl/jira-assistant#98]
Can row banding be added to Calendar/Worklogs Week View so it easier to see where to click for a particular time?

Using something like:
tr:nth-child(even) {
    background-color: #8dcdff21;
}

Adding Item Colors to the existing Calendar Configurations screen?

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC, This implementation is done in JA v2.44 and would be published within couple of days. Closing this ticket considering the implementation is done. Please feel free to reopen it if you feel something is not right.
