### ISSUE TITLE
Update Calendar/Worklogs Week view to be able to add worklog outside of working hours

### ISSUE THREAD

**Issue by EH-DUMAC** [shridhar-tl/jira-assistant#99]
Can the Calendar/Worklogs Week view be updated to expand/collapse hours outside of the configured normal working hours, for those times when additional work is put in?  We are on call after hours, and occasionally have to add in hours late at night or early morning.

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC - Please refer the screenshot. I hope this is the settings you would need to change. From left hand menu go to SETTINGS -> General menu -< General tab and change the highlighted settings and click Save button. Then navigate to Calendar page and you should have your calendar updated with appropriate time setting. If it did not get updated then try refreshing the page once and check.

![image](https://user-images.githubusercontent.com/37339683/67225465-e7800a80-f450-11e9-8c21-f0e0f57788b4.png)


Please let me know if this helps?

**Comment by EH-DUMAC** [comment]
I have had to set those to max of 00:00 to 23:00 just so I can add worklogs outside of normal working hours (although the calendar scrolling was broken this morning which someone else had already written up).  Working outside of normal hours does not happen very often, so was wondering if there was a way to have calendar only show the normal working hours (say some 8 hour time frame), but be able to easily expand and collapse times outside of this configurable working hours time frame for those rare occasions.  If I have to always have the Working Hours set to max for these rare cases, so be it, but was hoping the calendar could be updated.  Thanks.

**Comment by shridhar-tl** [comment]
I will check the feasibility on this requirement and get back to you.

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC, I know it has been too long since you asked this. But would like to let you know that this implementation was done in JA v2.44 and would be published in another couple of days. Look at the following snap show for your reference. Hence closing this issue as completed.

![image](https://user-images.githubusercontent.com/37339683/209751474-4ff30013-a1e4-4076-a628-54e4fa55ec46.png)
